import type { SolarTerm } from '../core/types.ts';

/**
 * 二十四节气通识内容（公历日期为约数，物候/农事为常见表述再创作）。
 * 非精确天文历书；用于文化互动教学。
 */
export const SOLAR_TERMS: SolarTerm[] = [
  {
    id: 'lichun',
    name: '立春',
    order: 1,
    season: 'spring',
    dateHint: '约 2 月 3 至 5 日',
    oneLiner: '岁之始，春气动。',
    phenology: '东风解冻',
    farming: '整地备耕，修整农具',
    verse: '律回岁晚冰霜少，春到人间草木知。',
    lore: '立春是二十四节气之首，也是四季轮回的起点。古人以「迎春」仪式感受新岁之气，提醒人们：时间重新打开。',
    glyph: '🌱',
    tint: '#7FB069',
  },
  {
    id: 'yushui',
    name: '雨水',
    order: 2,
    season: 'spring',
    dateHint: '约 2 月 18 至 20 日',
    oneLiner: '雪融为雨，润物无声。',
    phenology: '候雁北',
    farming: '春耕备播，注意防渍',
    verse: '好雨知时节，当春乃发生。',
    lore: '雨水不单是「开始下雨」，更是气温回升、降水形态由雪转雨的信号。农谚常说「雨水连绵是丰年」。',
    glyph: '💧',
    tint: '#6FA8C7',
  },
  {
    id: 'jingzhe',
    name: '惊蛰',
    order: 3,
    season: 'spring',
    dateHint: '约 3 月 5 至 7 日',
    oneLiner: '春雷一响，百虫出户。',
    phenology: '桃始华',
    farming: '春播关键期，防治虫害',
    verse: '微雨众卉新，一雷惊蛰始。',
    lore: '惊蛰之名，来自春雷惊醒蛰伏的虫豸。它也常被用来比喻「该醒的事醒了」，自然与人事同拍。',
    glyph: '⚡',
    tint: '#C9A24B',
  },
  {
    id: 'chunfen',
    name: '春分',
    order: 4,
    season: 'spring',
    dateHint: '约 3 月 20 至 22 日',
    oneLiner: '昼夜均分，阴阳相半。',
    phenology: '玄鸟至',
    farming: '适时播种，田间管理',
    verse: '春分雨脚落声微，柳岸斜风带客归。',
    lore: '春分时太阳直射赤道，昼夜大致等长。古人以「半」为美：一半光，一半影，正好校准生活的节奏。',
    glyph: '⚖️',
    tint: '#8FBC8F',
  },
  {
    id: 'qingming',
    name: '清明',
    order: 5,
    season: 'spring',
    dateHint: '约 4 月 4 至 6 日',
    oneLiner: '气清景明，慎终追远。',
    phenology: '桐始华',
    farming: '植树造林，春耕扫尾',
    verse: '清明时节雨纷纷，路上行人欲断魂。',
    lore: '清明既是节气，也是节日：一边踏青看新绿，一边祭扫寄哀思。它把「向前走」与「记得来处」写在同一阵春风里。',
    glyph: '🌿',
    tint: '#5C8A5E',
  },
  {
    id: 'guyu',
    name: '谷雨',
    order: 6,
    season: 'spring',
    dateHint: '约 4 月 19 至 21 日',
    oneLiner: '雨生百谷，春尽夏将至。',
    phenology: '萍始生',
    farming: '播种移栽，茶事繁忙',
    verse: '谷雨春光晓，山川黛色青。',
    lore: '谷雨是春季最后一个节气，「雨生百谷」概括了它对农业的意义。许多地方也把谷雨与采茶、祭仓颉等习俗相连。',
    glyph: '🌾',
    tint: '#9BC53D',
  },
  {
    id: 'lixia',
    name: '立夏',
    order: 7,
    season: 'summer',
    dateHint: '约 5 月 5 至 7 日',
    oneLiner: '夏之始，万物繁茂。',
    phenology: '蝼蝈鸣',
    farming: '查苗补苗，防旱保墒',
    verse: '绿树阴浓夏日长，楼台倒影入池塘。',
    lore: '立夏标志着春天结束、夏天开始。古人有「称人」等习俗，盼人像庄稼一样在夏天长得结实。',
    glyph: '☀️',
    tint: '#E0A458',
  },
  {
    id: 'xiaoman',
    name: '小满',
    order: 8,
    season: 'summer',
    dateHint: '约 5 月 20 至 22 日',
    oneLiner: '麦粒渐满，尚未大熟。',
    phenology: '苦菜秀',
    farming: '防麦田病害，备收夏粮',
    verse: '夜来南风起，小麦覆陇黄。',
    lore: '小满之名，说的是夏熟作物籽粒开始饱满，却还不到完全成熟。它提醒：成熟需要耐心，满而不溢。',
    glyph: '🫘',
    tint: '#D4A373',
  },
  {
    id: 'mangzhong',
    name: '芒种',
    order: 9,
    season: 'summer',
    dateHint: '约 6 月 5 至 7 日',
    oneLiner: '有芒之谷可种，农忙之极。',
    phenology: '螳螂生',
    farming: '抢收抢种，夏播关键期',
    verse: '时雨及芒种，四野皆插秧。',
    lore: '芒种是「忙种」的谐音写照：既要收麦，又要插秧。一年中最紧张的农事节点之一，把时间压成行动。',
    glyph: '🚜',
    tint: '#C9A227',
  },
  {
    id: 'xiazhi',
    name: '夏至',
    order: 10,
    season: 'summer',
    dateHint: '约 6 月 21 至 22 日',
    oneLiner: '白昼最长，阳极而至。',
    phenology: '鹿角解',
    farming: '中耕除草，防洪抗旱',
    verse: '昼晷已云极，宵漏自此长。',
    lore: '夏至时北半球白昼最长。古人从「至」字读出转折：盛极将衰，阳气到顶，阴气悄然回升。',
    glyph: '🔆',
    tint: '#E8B923',
  },
  {
    id: 'xiaoshu',
    name: '小暑',
    order: 11,
    season: 'summer',
    dateHint: '约 7 月 6 至 8 日',
    oneLiner: '暑气初盛，尚未酷热。',
    phenology: '温风至',
    farming: '田间管理，防台防涝',
    verse: '小暑不足热，还有二十天。',
    lore: '小暑意味着真正的炎热开始抬头。农事与生活都进入「与热相处」的阶段：劳作要趁早，休息要及时。',
    glyph: '🔥',
    tint: '#E07A3D',
  },
  {
    id: 'dashu',
    name: '大暑',
    order: 12,
    season: 'summer',
    dateHint: '约 7 月 22 至 24 日',
    oneLiner: '一年最热，伏中正盛。',
    phenology: '土润溽暑',
    farming: '抗旱保苗，抢收抢种',
    verse: '大暑连天热，稻花风里香。',
    lore: '大暑常与「三伏」重叠，是全年最热时段之一。它考验作物，也考验人的节奏：热不是敌人，是季节的性格。',
    glyph: '🌡️',
    tint: '#C82E21',
  },
  {
    id: 'liqiu',
    name: '立秋',
    order: 13,
    season: 'autumn',
    dateHint: '约 8 月 7 至 9 日',
    oneLiner: '秋气始来，暑犹未尽。',
    phenology: '凉风至',
    farming: '秋收准备，中晚稻管理',
    verse: '乳鸦啼散玉屏空，一枕新凉一扇风。',
    lore: '立秋是秋季开始的信号，但「秋老虎」仍可能发威。节气告诉我们：季节的切换是渐变，不是开关。',
    glyph: '🍃',
    tint: '#C87A3A',
  },
  {
    id: 'chushu',
    name: '处暑',
    order: 14,
    season: 'autumn',
    dateHint: '约 8 月 22 至 24 日',
    oneLiner: '暑气止息，凉意渐生。',
    phenology: '鹰乃祭鸟',
    farming: '抢收早秋，播种秋菜',
    verse: '处暑无三日，新凉直万金。',
    lore: '「处」有终止之意，处暑即「暑气到此为止」。天气开始转凉，人们也从避暑转向迎接秋实。',
    glyph: '🍂',
    tint: '#B86B3A',
  },
  {
    id: 'bailu',
    name: '白露',
    order: 15,
    season: 'autumn',
    dateHint: '约 9 月 7 至 9 日',
    oneLiner: '夜凉凝露，白而晶莹。',
    phenology: '鸿雁来',
    farming: '晚稻灌浆，秋收临近',
    verse: '蒹葭苍苍，白露为霜。',
    lore: '白露时节昼夜温差加大，清晨露水更明显。古人以「露」读气温变化，看得见的水珠，是看不见的秋气。',
    glyph: '✨',
    tint: '#A8C0C8',
  },
  {
    id: 'qiufen',
    name: '秋分',
    order: 16,
    season: 'autumn',
    dateHint: '约 9 月 22 至 24 日',
    oneLiner: '昼夜再均，秋半而至。',
    phenology: '雷始收声',
    farming: '秋收高峰，秋播启动',
    verse: '一年好景君须记，最是橙黄橘绿时。',
    lore: '秋分与春分对称，昼夜再次大致等长。它是收获与播种并进的节点，也是传统「祭月」时令的背景。',
    glyph: '🌕',
    tint: '#D4A574',
  },
  {
    id: 'hanlu',
    name: '寒露',
    order: 17,
    season: 'autumn',
    dateHint: '约 10 月 8 至 9 日',
    oneLiner: '露气转寒，草木黄落。',
    phenology: '菊有黄华',
    farming: '抢收晚秋，冬小麦播种',
    verse: '寒露时节百谷成，田家处处有歌声。',
    lore: '寒露比白露更冷一分，露水带寒意。它是深秋的入口：景色更疏朗，农事更紧迫。',
    glyph: '🌼',
    tint: '#C9A24B',
  },
  {
    id: 'shuangjiang',
    name: '霜降',
    order: 18,
    season: 'autumn',
    dateHint: '约 10 月 23 至 24 日',
    oneLiner: '初霜将至，秋尽冬将临。',
    phenology: '豺乃祭兽',
    farming: '秋收扫尾，防霜护菜',
    verse: '霜降碧天静，秋事促征鸿。',
    lore: '霜降是秋季最后一个节气。有霜无霜因地域而异，但「霜降」作为物候符号，提示人们：该收藏的收藏，该准备过冬的准备。',
    glyph: '❄️',
    tint: '#8FA8B8',
  },
  {
    id: 'lidong',
    name: '立冬',
    order: 19,
    season: 'winter',
    dateHint: '约 11 月 7 至 8 日',
    oneLiner: '冬之始，万物收藏。',
    phenology: '水始冰',
    farming: '冬藏农具，保护越冬作物',
    verse: '立冬补冬，补嘴空。',
    lore: '立冬标志着冬季开始。在农耕社会里，「冬」不只是冷，更是「藏」，把一年的劳动成果与体力一起安顿下来。',
    glyph: '🧥',
    tint: '#6A8CA8',
  },
  {
    id: 'xiaoxue',
    name: '小雪',
    order: 20,
    season: 'winter',
    dateHint: '约 11 月 22 至 23 日',
    oneLiner: '气寒而雪未盛。',
    phenology: '虹藏不见',
    farming: '冬修水利，积肥造肥',
    verse: '小雪雪满天，来年是丰年。',
    lore: '小雪时节，北方可能开始飘雪，南方多仍是阴冷。它提醒：冷是渐进的，准备也可以分步完成。',
    glyph: '🌨️',
    tint: '#9BB0C1',
  },
  {
    id: 'daxue',
    name: '大雪',
    order: 21,
    season: 'winter',
    dateHint: '约 12 月 6 至 8 日',
    oneLiner: '雪将盛，寒将深。',
    phenology: '鹖鴠不鸣',
    farming: '防寒防冻，保护畜禽',
    verse: '大雪压青松，青松挺且直。',
    lore: '大雪并不保证「下大雪」，而是表示降雪概率与寒意增强。雪被古人看作「瑞」，它埋藏害虫，也滋润来年。',
    glyph: '⛄',
    tint: '#B8C7D4',
  },
  {
    id: 'dongzhi',
    name: '冬至',
    order: 22,
    season: 'winter',
    dateHint: '约 12 月 21 至 23 日',
    oneLiner: '白昼最短，一阳来复。',
    phenology: '蚯蚓结',
    farming: '兴修水利，副业生产',
    verse: '冬至阳生春又来。',
    lore: '冬至是「阴极而阳生」的节点：白昼最短之后，光开始一点点回来。许多地方以饺子或汤圆过节，把希望做成可吃的形状。',
    glyph: '🌑',
    tint: '#5C7A94',
  },
  {
    id: 'xiaohan',
    name: '小寒',
    order: 23,
    season: 'winter',
    dateHint: '约 1 月 5 至 7 日',
    oneLiner: '寒气渐积，尚未极冷。',
    phenology: '雁北乡',
    farming: '防寒保暖，腊月准备',
    verse: '小寒连大吕，欢鹊垒新巢。',
    lore: '小寒常进入一年中最冷的时段。名字却带着分寸：「小」不是不冷，而是冷还有余地，后面还有大寒。',
    glyph: '🧊',
    tint: '#7A9BB5',
  },
  {
    id: 'dahan',
    name: '大寒',
    order: 24,
    season: 'winter',
    dateHint: '约 1 月 20 至 21 日',
    oneLiner: '岁终之寒，春将不远。',
    phenology: '水泽腹坚',
    farming: '积肥造肥，备耕迎春',
    verse: '大寒到顶点，日后天渐暖。',
    lore: '大寒是二十四节气的终点，也是下一轮立春的前夜。寒到极处，正是回暖的伏笔，年轮在此闭合，又重新打开。',
    glyph: '🏔️',
    tint: '#4E6E8A',
  },
];

export function getTerm(id: string): SolarTerm | undefined {
  return SOLAR_TERMS.find((t) => t.id === id);
}

export function termsBySeason(season: SolarTerm['season']): SolarTerm[] {
  return SOLAR_TERMS.filter((t) => t.season === season).sort((a, b) => a.order - b.order);
}

export function termsInOrder(): SolarTerm[] {
  return [...SOLAR_TERMS].sort((a, b) => a.order - b.order);
}
