import type { LoreCard, QuizOption } from '../core/types';
import {
  BOARD,
  kitCamel,
  kitHornCup,
  kitHorse,
  kitPassGate,
  kitSaddle,
} from './shapeKits.ts';

/** 塞北 R05 · 20 张 · 草原丝路、马驼、关隘、互鉴 */

function shape(pieces: ReturnType<typeof kitHorse>): LoreCard['restore'] {
  return { kind: 'shape', board: { ...BOARD }, pieces };
}
function quiz(prompt: string, options: QuizOption[], explain: string): LoreCard['restore'] {
  return { kind: 'quiz', prompt, options, explain };
}

const SRC =
  '中国古代北方草原与丝路交通通识；公开博物馆与历史地理公教。本展示为再创作示意，非正式馆藏复制。';

export const SAIBEI_ARTIFACTS: LoreCard[] = [
  {
    id: 'A-R05-SR-001',
    name: '胡马意象',
    rarity: 'SR',
    types: ['folk'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L01'],
    oneLiner: '马是草原机动与诗意的共同主角。',
    coreLore:
      '在北方草原与边地交通中，马承担骑乘、驮运与礼仪象征。认识「马」，是理解塞北生活节奏与军旅、商旅记忆的第一课——不是要学会骑马技术，而是看见文明如何与动物协作。',
    source: SRC,
    todayLink: '今天的赛马会与牧区生活，仍让「马」保持公共文化温度。',
    tellable: '塞北的路，有一半写在马背上。',
    restore: shape(kitHorse()),
  },
  {
    id: 'A-R05-R-002',
    name: '骆驼商队意象',
    rarity: 'R',
    types: ['folk'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L02'],
    oneLiner: '双峰驼耐渴负重，是沙漠绿洲路上的活舟。',
    coreLore:
      '骆驼适应干旱环境，是丝路商队的重要运力。看见驼峰，就想起绿洲之间的漫长距离——贸易不只运送货物，也运送技术、信仰与故事。',
    source: SRC,
    todayLink: '博物馆里的驼队陶俑，是把商路冻成的雕塑。',
    tellable: '骆驼用沉默，走过比话还长的路。',
    restore: shape(kitCamel()),
  },
  {
    id: 'A-R05-SR-003',
    name: '关隘城楼意象',
    rarity: 'SR',
    types: ['concept', 'folk'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L03'],
    oneLiner: '门洞与敌楼，把「边界」变成可以站上去的建筑。',
    coreLore:
      '关隘是控制交通与防卫的节点，也是文化接触的前线。它既分隔又连接：人、货、消息从门洞通过。理解关隘，有助于读懂边塞诗与长城叙事的空间背景。',
    source: SRC,
    todayLink: '今天的口岸与高铁站，仍是「关」的现代变体。',
    tellable: '关不是终点，是两种风相遇的门槛。',
    restore: shape(kitPassGate()),
  },
  {
    id: 'A-R05-R-004',
    name: '马鞍',
    rarity: 'R',
    types: ['craft'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L01'],
    oneLiner: '鞍把人和马的力量接到同一条路上。',
    coreLore:
      '马鞍是骑乘的关键装具，结构影响舒适与稳定。草原与边地的鞍具常有鲜明装饰，说明实用与审美可以骑在一起。',
    source: SRC,
    todayLink: '任何「接口设计」——把两端连起来——都值得被看见。',
    tellable: '好鞍不说话，却让千里变得可能。',
    restore: shape(kitSaddle()),
  },
  {
    id: 'A-R05-R-005',
    name: '角杯意象',
    rarity: 'R',
    types: ['craft'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L04'],
    oneLiner: '以角为杯的宴饮形象，带着草原宴席的手感。',
    coreLore:
      '角杯等饮酒器在欧亚草原文化交流中常被提及，是宴饮与礼仪的物证之一。本卡建立「器形来自角」的印象，具体谱系以考古研究为准。',
    source: SRC,
    todayLink: '酒器总在讲：人们如何分享与结盟。',
    tellable: '角杯一倾，风里也有酒香的记忆。',
    restore: shape(kitHornCup()),
  },
  {
    id: 'A-R05-N-006',
    name: '塞北知一张',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L05'],
    oneLiner: '塞北：长城以北与边地交通的文化地理印象。',
    coreLore:
      '「塞北」在诗文与史地中常指长城以北或北方边地，本展区用它指草原—绿洲—关隘交织的文化气质：机动、互市、边塞诗与丝路余韵，而非单一民族标签。',
    source: '历史地理与文学通识。',
    todayLink: '读边塞诗时，可把「风沙」还原成具体的路与关。',
    tellable: '塞北是地图上的冷色，也是商路上的热茶。',
    restore: quiz(
      '本展区「塞北」主要指？',
      [
        { id: 'a', text: '北方边地与交通互市的文化气质', correct: true },
        { id: 'b', text: '江南园林专有名词', correct: false },
        { id: 'c', text: '仅指现代一个地铁站', correct: false },
      ],
      '文化气质展区。',
    ),
  },
  {
    id: 'A-R05-N-007',
    name: '丝路是路网',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L02'],
    oneLiner: '不是一条直线，而是绿洲串起的网络。',
    coreLore:
      '「丝绸之路」是后代概括的名称，实际是多条商路与绿洲城镇组成的交通网。理解「网」而不是「单线」，更能看见多元民族与技术如何在路上相遇。',
    source: SRC,
    todayLink: '今天的国际班列与航线，仍在续写「路网」故事。',
    tellable: '丝路像一串念珠，每颗绿洲都是一念。',
    restore: quiz(
      '更准确理解丝路的说法是？',
      [
        { id: 'a', text: '多条道路与绿洲组成的交通网络', correct: true },
        { id: 'b', text: '地球上唯一的一条笔直公路', correct: false },
        { id: 'c', text: '只存在于游戏副本', correct: false },
      ],
      '网络而非单线。',
    ),
  },
  {
    id: 'A-R05-N-008',
    name: '互市与交换',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L03'],
    oneLiner: '边界上的市场，让刀剑有时让位于秤杆。',
    coreLore:
      '历史上边地存在互市等贸易安排，牲畜、皮毛、茶叶、丝绸等在不同时期进入交换。互市提醒我们：冲突不是边地关系的唯一剧本。',
    source: SRC,
    todayLink: '贸易博览会是互市精神的现代回声之一。',
    tellable: '有的和平，是一车茶和一群马谈出来的。',
    restore: quiz(
      '「互市」更接近？',
      [
        { id: 'a', text: '边地有组织的贸易交换', correct: true },
        { id: 'b', text: '禁止一切往来', correct: false },
        { id: 'c', text: '只允许战争', correct: false },
      ],
      '交换也是关系。',
    ),
  },
  {
    id: 'A-R05-N-009',
    name: '边塞诗入口',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L06'],
    oneLiner: '诗把风沙、月光与乡愁写成可背诵的记忆。',
    coreLore:
      '边塞诗是唐诗等传统中的重要题材，写征人、边疆风光与家国之情。它不是军事手册，却让后人用情感记住边地。可与关隘、马匹意象对照阅读。',
    source: '古典文学通识。',
    todayLink: '课堂上的名句，背后是具体的路与人。',
    tellable: '边塞诗是风沙里的信，写给中原的灯。',
    restore: quiz(
      '边塞诗主要帮助我们理解？',
      [
        { id: 'a', text: '边地经验的文学与情感表达', correct: true },
        { id: 'b', text: '现代编程语法', correct: false },
        { id: 'c', text: '只描写热带雨林', correct: false },
      ],
      '文学入口。',
    ),
  },
  {
    id: 'A-R05-N-010',
    name: '胡汉不是对立标签',
    rarity: 'N',
    types: ['concept', 'ethics'],
    authTag: 'public_edu',
    region: 'R05',
    learnIds: ['R05-X-ethics'],
    oneLiner: '历史上的交往复杂，忌用简单对立概括一切。',
    coreLore:
      '「胡」「汉」等历史用语在不同时代含义不同。学习边地文化时，应避免把复杂人群关系简化成永久敌对，而看见贸易、通婚、技艺与冲突并存的真实层次。',
    source: '公共历史教育倡导。',
    todayLink: '尊重多元，是读历史最基本的礼貌。',
    tellable: '路上走的不只是敌我，还有货物与歌。',
    restore: quiz(
      '理解古代边地关系，更合适的是？',
      [
        { id: 'a', text: '看见贸易、交流与冲突的多重面', correct: true },
        { id: 'b', text: '只用仇恨概括全部历史', correct: false },
        { id: 'c', text: '否认任何文化接触', correct: false },
      ],
      '复杂优于脸谱。',
    ),
  },
  {
    id: 'A-R05-R-011',
    name: '毡帐印象',
    rarity: 'R',
    types: ['folk'],
    authTag: 'folk',
    region: 'R05',
    learnIds: ['R05-L01'],
    oneLiner: '可拆可迁的家，跟着水草移动。',
    coreLore:
      '毡帐（穹庐等）是游牧生活的重要居住形式，便于迁徙。它说明「家」不一定钉死在砖墙上，也可以是跟着生态节奏移动的结构。',
    source: SRC,
    todayLink: '现代露营帐篷是遥远的技术亲戚。',
    tellable: '毡帐一立，草原就有了一盏灯的中心。',
    restore: quiz(
      '毡帐作为居所，突出特点是？',
      [
        { id: 'a', text: '便于迁徙的居住形式', correct: true },
        { id: 'b', text: '只能建在摩天楼顶', correct: false },
        { id: 'c', text: '与游牧生活无关', correct: false },
      ],
      '移动的家。',
    ),
  },
  {
    id: 'A-R05-N-012',
    name: '皮毛与技艺',
    rarity: 'N',
    types: ['craft', 'concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L04'],
    oneLiner: '御寒材料背后，是一整套手艺与生态知识。',
    coreLore:
      '皮毛加工与御寒服饰是北方生活的关键技艺。材料来自生态，技艺来自世代经验。欣赏相关文物时，先问「它如何让人活过冬天」。',
    source: SRC,
    todayLink: '现代冲锋衣，是另一个时代的御寒答案。',
    tellable: '暖，有时是一种被缝起来的智慧。',
    restore: quiz(
      '理解北方皮毛器物，优先关注？',
      [
        { id: 'a', text: '御寒功能与制作技艺', correct: true },
        { id: 'b', text: '是否能当手机壳', correct: false },
        { id: 'c', text: '完全无实用意义', correct: false },
      ],
      '功能与技艺。',
    ),
  },
  {
    id: 'A-R05-N-013',
    name: '音乐与长调印象',
    rarity: 'N',
    types: ['musical', 'concept'],
    authTag: 'folk',
    region: 'R05',
    learnIds: ['R05-L06'],
    oneLiner: '辽阔的音域，像把地平线唱长。',
    coreLore:
      '包括长调在内的草原音乐传统，以悠长旋律著称，是非物质文化遗产的重要组成。本卡只建立「声音也有地平线」的印象，具体曲种请以正式传承介绍为准。',
    source: '非遗与民族音乐公教。',
    todayLink: '音乐会上的长调，是把风翻译成人声。',
    tellable: '有的歌，一句就能走出很远。',
    restore: quiz(
      '草原长调给人的常见印象是？',
      [
        { id: 'a', text: '旋律悠长，气息开阔', correct: true },
        { id: 'b', text: '只能是电子节拍', correct: false },
        { id: 'c', text: '禁止任何人演唱', correct: false },
      ],
      '声音的地平线。',
    ),
  },
  {
    id: 'A-R05-N-014',
    name: '对照五区',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L05'],
    oneLiner: '鼎、凤、纵目、瓷、马——五张不同的地图。',
    coreLore:
      '中原礼乐、楚地浪漫、巴蜀奇器、江南雅致、塞北交通：五区并置，是为了练习「换一双眼睛看中国」。你可以有最爱，但别让最爱变成唯一。',
    source: '本游戏展区课程汇总。',
    todayLink: '旅行清单可以按这五张地图来列。',
    tellable: '五区走完，我的中国变厚了。',
    restore: quiz(
      '多展区对照学习的目的是？',
      [
        { id: 'a', text: '理解多元气质，避免单一想象', correct: true },
        { id: 'b', text: '证明只有一地有文化', correct: false },
        { id: 'c', text: '强制付费', correct: false },
      ],
      '多元并置。',
    ),
  },
  {
    id: 'A-R05-N-015',
    name: '长城的多重角色',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L03'],
    oneLiner: '墙可以是防，也可以是线与记忆。',
    coreLore:
      '长城是长时段、多地段的军事与边政工程系统，也是今日世界遗产与公共记忆。理解它，既看防卫功能，也看沿线社会与文化遗产保护。',
    source: '长城学与文保公教通识。',
    todayLink: '登长城请文明游览，保护砖石。',
    tellable: '长城是墙，也是一条很长的说明书。',
    restore: quiz(
      '对待长城遗产，更合适的是？',
      [
        { id: 'a', text: '理解其历史功能并参与保护', correct: true },
        { id: 'b', text: '刻画留名破坏遗址', correct: false },
        { id: 'c', text: '否认其任何历史存在', correct: false },
      ],
      '理解 + 保护。',
    ),
  },
  {
    id: 'A-R05-R-016',
    name: '玉门/阳关印象',
    rarity: 'R',
    types: ['classic', 'concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L06'],
    oneLiner: '诗里的关名，把地理变成乡愁的坐标。',
    coreLore:
      '玉门、阳关等关名因边塞诗而广为人知，成为送别与远行的文化符号。地理实体与文学意象叠合，是中国人记忆空间的独特方式。',
    source: '古典文学与历史地理通识。',
    todayLink: '「西出阳关」至今仍被用来形容远行。',
    tellable: '有的关，城砖可朽，诗句不朽。',
    restore: quiz(
      '玉门、阳关在文化记忆里，常象征？',
      [
        { id: 'a', text: '边地远行与送别', correct: true },
        { id: 'b', text: '江南采莲节专名', correct: false },
        { id: 'c', text: '现代机场登机口编号', correct: false },
      ],
      '诗与关。',
    ),
  },
  {
    id: 'A-R05-N-017',
    name: '生态与敬畏',
    rarity: 'N',
    types: ['concept', 'ethics'],
    authTag: 'public_edu',
    region: 'R05',
    learnIds: ['R05-X-ethics'],
    oneLiner: '草原与荒漠脆弱，文化欣赏不该变成破坏。',
    coreLore:
      '北方生态对过度开发敏感。学习游牧与丝路文化时，应同步建立生态保护意识：不破坏植被、不惊扰野生动物、不传播违法盗猎信息。',
    source: '生态文明公共教育。',
    todayLink: '去牧区旅行，把垃圾带走，把尊重留下。',
    tellable: '真正的辽阔，需要被轻轻对待。',
    restore: quiz(
      '在草原旅行，更合适的是？',
      [
        { id: 'a', text: '保护生态、尊重当地规范', correct: true },
        { id: 'b', text: '随意破坏草场', correct: false },
        { id: 'c', text: '鼓励盗猎炫耀', correct: false },
      ],
      '文化与生态同行。',
    ),
  },
  {
    id: 'A-R05-N-018',
    name: '粟特与中介印象',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L02'],
    oneLiner: '路上常有擅长贸易与翻译的中介人群。',
    coreLore:
      '历史上包括粟特人在内的许多群体曾在丝路贸易与文化翻译中扮演角色。本卡只建立「商路需要中介与多语」的印象，避免单一民族叙事。',
    source: SRC,
    todayLink: '翻译与物流，仍是全球化的看不见桥梁。',
    tellable: '有人贩运丝绸，也有人贩运词语。',
    restore: quiz(
      '丝路贸易中「中介」的作用更接近？',
      [
        { id: 'a', text: '连接不同地区的货物与信息', correct: true },
        { id: 'b', text: '让所有交流停止', correct: false },
        { id: 'c', text: '与贸易无关', correct: false },
      ],
      '连接者。',
    ),
  },
  {
    id: 'A-R05-N-019',
    name: '看展：边地文物',
    rarity: 'N',
    types: ['concept'],
    authTag: 'public_edu',
    region: 'R05',
    learnIds: ['R05-X-museum'],
    oneLiner: '一件带异域纹样的器物，可能是一场漫长对话的句号。',
    coreLore:
      '博物馆中的金银器、玻璃、织物残片等，常显示跨区域风格。看展时问：它可能从哪条路来？与本地样式有何不同？比急着下「神秘」结论更有收获。',
    source: '博物馆公教方法。',
    todayLink: '说明牌上的出土地与年代，是推理的线索。',
    tellable: '有的文物，脚印比铭文更长。',
    restore: quiz(
      '看到风格混杂的边地文物，更推荐？',
      [
        { id: 'a', text: '结合出土地与风格比较提问', correct: true },
        { id: 'b', text: '立刻编造奇幻阴谋', correct: false },
        { id: 'c', text: '拒绝阅读任何说明', correct: false },
      ],
      '提问优于武断。',
    ),
  },
  {
    id: 'A-R05-SR-020',
    name: '塞北小谱',
    rarity: 'SR',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R05',
    learnIds: ['R05-L01', 'R05-L02', 'R05-L03'],
    oneLiner: '马、驼、关、诗——带走塞北四印象。',
    coreLore:
      '塞北展区希望你带走：马与驼的运力；关隘的门槛；丝路作为网络；边塞诗的情感；以及互市与互鉴的可能。它让「中国」的北方边境，从冷色块变成可走的路。',
    source: '本区域课程纲要汇总。',
    todayLink: '下一首边塞诗，试着配一匹马和一座关。',
    tellable: '塞北这一路，我记住了马蹄、驼铃、门洞和诗。',
    restore: quiz(
      '塞北展区最核心的学习主题更接近？',
      [
        { id: 'a', text: '马驼交通·关隘丝路·互市与边塞诗', correct: true },
        { id: 'b', text: '只学江南青花绘制工序', correct: false },
        { id: 'c', text: '现代芯片光刻参数', correct: false },
      ],
      '路与关是主轴。',
    ),
  },
];
