import type { LoreCard, QuizOption } from '../core/types';
import {
  BOARD,
  kitBoat,
  kitChime,
  kitDrum,
  kitEarCup,
  kitPhoenix,
  kitScroll,
  kitTigerPhoenix,
  kitZun,
} from './shapeKits.ts';

/**
 * 楚地 R02 · 约 20 张文化卡
 * 主题：凤鸟、漆器、江汉、楚辞意象、帛画、礼乐南枝（克制表述）
 */

function shape(pieces: ReturnType<typeof kitPhoenix>): LoreCard['restore'] {
  return { kind: 'shape', board: { ...BOARD }, pieces };
}

function quiz(prompt: string, options: QuizOption[], explain: string): LoreCard['restore'] {
  return { kind: 'quiz', prompt, options, explain };
}

const SRC = '中国古代南方/楚文化通识；公开博物馆与教材公教表述。本展示为再创作示意，非正式馆藏复制。';
const SRC_LIT = '《楚辞》及相关文学史通识；公开注本与公教介绍。';

export const CHU_ARTIFACTS: LoreCard[] = [
  {
    id: 'A-R02-SR-001',
    name: '凤鸟纹饰',
    rarity: 'SR',
    types: ['pattern', 'bronze'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L01'],
    oneLiner: '舒展的凤鸟形象，是楚地装饰里极醒目的母题。',
    coreLore:
      '凤鸟纹在楚地青铜、漆器与丝织装饰中十分常见，姿态往往更舒展、浪漫。认识凤鸟纹，是进入楚地视觉世界的一把钥匙——与中原兽面的庄严形成有趣对照。',
    source: SRC,
    todayLink: '今天的国风设计里，「楚凤」仍是南方浪漫的常用符号。',
    tellable: '楚地的凤，翅膀张得更开，像风本身。',
    restore: shape(kitPhoenix()),
  },
  {
    id: 'A-R02-R-002',
    name: '漆耳杯',
    rarity: 'R',
    types: ['lacquer'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L02'],
    oneLiner: '双耳小杯，漆色温润，是楚地漆器的亲切面孔。',
    coreLore:
      '耳杯（羽觞）是古代常见饮酒器，楚墓出土漆耳杯尤以色彩与完好度令人印象深刻。漆器提醒我们：除了青铜的冷光，还有木与漆的温暖光泽。',
    source: SRC,
    todayLink: '「流觞曲水」的文学记忆里，就有这类双耳杯的影子。',
    tellable: '双手托起耳杯，像托起一小片会反光的夜。',
    restore: shape(kitEarCup()),
  },
  {
    id: 'A-R02-N-003',
    name: '楚地知一张',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L03'],
    oneLiner: '楚：江汉之间的古国与文化传统。',
    coreLore:
      '楚是先秦重要古国，活动范围大致与江汉流域等相关，文化上常被概括为浪漫、重巫祀与艺术表现力强。本展区用「楚地」指这一文化气质与文物印象，而非精确疆域课。',
    source: '先秦史与区域文化通识。',
    todayLink: '今天说「楚文化」，多指这一历史传统与艺术风格。',
    tellable: '楚地不只是方向，更是一种开得很满的审美。',
    restore: quiz(
      '本展区「楚地」主要用来指？',
      [
        { id: 'a', text: '江汉一带的古国文化与艺术气质', correct: true },
        { id: 'b', text: '现代某一个快递分区代码', correct: false },
        { id: 'c', text: '只有沙漠绿洲文明', correct: false },
      ],
      '文化展区名，服务学习主题。',
    ),
  },
  {
    id: 'A-R02-SR-004',
    name: '虎座凤架鼓意象',
    rarity: 'SR',
    types: ['lacquer', 'musical'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L01', 'R02-L04'],
    oneLiner: '虎座之上立凤，凤间悬鼓——楚地礼乐的经典构图印象。',
    coreLore:
      '虎座凤架鼓是楚地极具识别度的乐器/礼器组合意象：虎为座、凤为架、中悬鼓。它把神兽想象与声音仪式结合在一起，是理解楚地「看得见的乐」的重要入口。',
    source: SRC,
    todayLink: '博物馆里若看到彩绘木雕凤鸟与鼓，不妨慢慢围着走一圈。',
    tellable: '楚人把鼓架在凤的翅膀之间——乐，也要有翅膀。',
    restore: shape(kitTigerPhoenix()),
  },
  {
    id: 'A-R02-R-005',
    name: '建鼓',
    rarity: 'R',
    types: ['musical'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L04'],
    oneLiner: '立于座上的鼓，是仪式与节奏的中心。',
    coreLore:
      '建鼓是一种立鼓，常见于礼仪与军乐等语境。在楚地文物与图像中，鼓与凤架等组合强化了「声音也是礼」的印象。',
    source: SRC,
    todayLink: '节庆里的鼓点，仍在用节奏召集人群。',
    tellable: '鼓一响，场合就有了心跳。',
    restore: shape(kitDrum()),
  },
  {
    id: 'A-R02-R-006',
    name: '帛画卷意象',
    rarity: 'R',
    types: ['textile', 'painting'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L05'],
    oneLiner: '丝帛上的画，轻而持久的南方记忆。',
    coreLore:
      '楚地出土帛画是中国早期绘画史的重要材料，题材常与引魂升天、龙凤等想象相关。对本展区而言，先建立「丝帛也能承载图像与信仰叙事」的印象即可。',
    source: SRC,
    todayLink: '绢本、纸本之前，丝帛已是图像的载体。',
    tellable: '帛画画在会呼吸的丝上，像风也会停驻一会儿。',
    restore: shape(kitScroll()),
  },
  {
    id: 'A-R02-N-007',
    name: '楚辞入门',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L06'],
    oneLiner: '《楚辞》是南方诗歌传统的重要源头。',
    coreLore:
      '《楚辞》是中国文学史上与《诗经》并称的重要诗歌总集/传统，与楚地语言、风物、神话想象密切相关。先记住：它代表一种更缠绵、更浪漫的古典诗风入口。',
    source: SRC_LIT,
    todayLink: '今天读到「香草美人」等意象，常能追溯到楚辞传统。',
    tellable: '《诗经》像大地的歌，楚辞像江上的风。',
    restore: quiz(
      '《楚辞》在通识里更常被用来代表？',
      [
        { id: 'a', text: '与楚地相关的古典诗歌传统', correct: true },
        { id: 'b', text: '现代汽车维修手册', correct: false },
        { id: 'c', text: '只有英文十四行诗', correct: false },
      ],
      '文学传统入口，不要求背全文。',
    ),
  },
  {
    id: 'A-R02-R-008',
    name: '香草意象',
    rarity: 'R',
    types: ['classic', 'concept'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L06'],
    oneLiner: '香草在楚辞里，常象征美好与高洁。',
    coreLore:
      '楚辞传统中，香草、美人等意象常被用来象征美德、理想与情感。这是文学象征，不是植物图鉴课；理解「以香草喻德」即可进入阅读门槛。',
    source: SRC_LIT,
    todayLink: '现代汉语里夸人「兰心蕙质」，仍有古典余韵。',
    tellable: '楚人把美德，做成可以闻见的草。',
    restore: quiz(
      '楚辞里的「香草」更常被理解为？',
      [
        { id: 'a', text: '象征美好与高洁的文学意象', correct: true },
        { id: 'b', text: '超市香料区条形码', correct: false },
        { id: 'c', text: '禁止使用的植物名录', correct: false },
      ],
      '象征阅读，不考植物分类。',
    ),
  },
  {
    id: 'A-R02-R-009',
    name: '江上舟',
    rarity: 'R',
    types: ['folk'],
    authTag: 'folk',
    region: 'R02',
    learnIds: ['R02-L03'],
    oneLiner: '江汉多水，舟是南方生活的基本道具。',
    coreLore:
      '楚地河网纵横，舟楫是交通、生计与文学意象的重要部分。认识「水与舟」，有助于理解为何楚艺术与诗歌常显得流动、开阔。',
    source: '区域地理与民俗通识。',
    todayLink: '渡口、码头与江景，仍是南方城市的日常诗意。',
    tellable: '楚地的路，有一半写在水上。',
    restore: shape(kitBoat()),
  },
  {
    id: 'A-R02-N-010',
    name: '中原与楚地对照',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L03'],
    oneLiner: '庄严与浪漫，是两种可并存的美。',
    coreLore:
      '中原礼器常给人以秩序、庄重之感；楚地艺术常被概括为浪漫、灵动、色彩饱满。对照不是比高下，而是学会看见文明的多样性。',
    source: '区域文化比较通识。',
    todayLink: '旅行时南北审美的差异，往往比地图更动人。',
    tellable: '中原像鼎，楚地像凤——都是中国的脸。',
    restore: quiz(
      '比较中原与楚地艺术气质，更合适的态度是？',
      [
        { id: 'a', text: '看见不同审美，理解多样性', correct: true },
        { id: 'b', text: '只保留一个、消灭另一个', correct: false },
        { id: 'c', text: '完全没有区别', correct: false },
      ],
      '对照为了理解，不是对立。',
    ),
  },
  {
    id: 'A-R02-R-011',
    name: '楚式铜器印象',
    rarity: 'R',
    types: ['bronze'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L01'],
    oneLiner: '楚地青铜也有自己的器形与纹样脾气。',
    coreLore:
      '楚地青铜器在器类、纹饰上既与中原系统交流，也发展出地方特色（如某些繁复纹饰与器形）。入门阶段记住：青铜不是中原专利，南方同样铸鼎钟、写风格。',
    source: SRC,
    todayLink: '博物馆分区陈列时，可比较南北器表的「疏密与动势」。',
    tellable: '同样是青铜，楚器的线条更爱跳舞。',
    restore: shape(kitZun()),
  },
  {
    id: 'A-R02-R-012',
    name: '编钟·南音印象',
    rarity: 'R',
    types: ['musical', 'bronze'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L04'],
    oneLiner: '南方诸侯也有巍然成组的钟。',
    coreLore:
      '包括楚地在内的南方地区，同样出土重要编钟。它说明礼乐制度与乐器技术曾在广阔地域流动。结合中原展区的编钟卡，可形成「乐在四方」的完整印象。',
    source: SRC,
    todayLink: '著名的曾侯乙编钟出土地与楚文化圈关系密切，值得专程了解。',
    tellable: '南边的钟，一样能把礼乐敲得很满。',
    restore: shape(kitChime()),
  },
  {
    id: 'A-R02-N-013',
    name: '漆：木与光',
    rarity: 'N',
    types: ['concept', 'lacquer'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L02'],
    oneLiner: '大漆附着于木，生成可触摸的光泽。',
    coreLore:
      '中国传统漆工艺以大漆等材料反复髹饰木胎等底材，形成耐用而富有光泽的表面，并可描金彩绘。楚地漆器是认识这一工艺的绝佳窗口。',
    source: SRC,
    todayLink: '现代漆器与漆艺文创，仍在延续这门「时间叠出来的光」。',
    tellable: '漆器的亮，是一层层时间刷出来的。',
    restore: quiz(
      '传统漆器常见的做法更接近？',
      [
        { id: 'a', text: '在胎骨上反复髹漆并可装饰', correct: true },
        { id: 'b', text: '只用透明玻璃一次吹制', correct: false },
        { id: 'c', text: '完全是塑料注塑', correct: false },
      ],
      '髹漆是时间工艺。',
    ),
  },
  {
    id: 'A-R02-N-014',
    name: '巫祀表述边界',
    rarity: 'N',
    types: ['concept', 'ethics'],
    authTag: 'public_edu',
    region: 'R02',
    learnIds: ['R02-X-ethics'],
    oneLiner: '理解历史中的巫祀文化，不等于宣导迷信。',
    coreLore:
      '楚文化常被提到重巫祀、想象丰富。本展览以艺术与历史理解为主，不教授任何「操作方法」，也不鼓励封建迷信。把神怪当文化遗产来读，把科学当生活原则来守。',
    source: '公共文化教育与法规倡导的表述原则。',
    todayLink: '欣赏神话，过好现实——两不误。',
    tellable: '我读楚的想象，但不拿幻想替代生活的判断。',
    restore: quiz(
      '在本展览中对待楚地巫祀相关内容，更合适的是？',
      [
        { id: 'a', text: '作为历史文化与艺术来理解', correct: true },
        { id: 'b', text: '按展览教的方法去搞迷信活动', correct: false },
        { id: 'c', text: '完全禁止阅读任何神话', correct: false },
      ],
      '文化理解 ≠ 迷信实践。',
    ),
  },
  {
    id: 'A-R02-R-015',
    name: '龙凤组合印象',
    rarity: 'R',
    types: ['pattern', 'classic'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L01', 'R02-L05'],
    oneLiner: '龙与凤常一起出现在楚地图像里。',
    coreLore:
      '楚地帛画与器物纹饰中，龙凤并见的情况不少，构图充满动势。入门只要求能辨认：这是「神话动物一起出现的画面」，并与中原兽面纹的对称庄严做对比记忆。',
    source: SRC,
    todayLink: '婚礼与节庆中的「龙凤」符号，有更长的历史回声。',
    tellable: '楚画里的龙凤，像两道一起走的风。',
    restore: quiz(
      '看到楚地「龙凤」图像，入门时更该先做什么？',
      [
        { id: 'a', text: '辨认母题，并感受构图动势', correct: true },
        { id: 'b', text: '立刻估价拍卖', correct: false },
        { id: 'c', text: '认定只是现代商标', correct: false },
      ],
      '先认后解。',
    ),
  },
  {
    id: 'A-R02-N-016',
    name: '江汉与物产',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L03'],
    oneLiner: '水网、林木与矿物，托起工艺与想象。',
    coreLore:
      '江汉平原及周边山地提供了农林与矿冶条件，使漆木器、青铜等工艺得以发展。地理不是宿命论，但有助于理解「为什么这里出现这样的物」。',
    source: '历史地理通识。',
    todayLink: '一方水土养一方物，也养一方审美。',
    tellable: '楚地的美，先有江和树，才有漆和凤。',
    restore: quiz(
      '理解楚地漆器发达，较有帮助的背景是？',
      [
        { id: 'a', text: '林木等资源与工艺传统', correct: true },
        { id: 'b', text: '完全没有树木的冰川区', correct: false },
        { id: 'c', text: '只因为现代化工厂', correct: false },
      ],
      '物产与工艺相关，但不唯一。',
    ),
  },
  {
    id: 'A-R02-R-017',
    name: '彩绘木器印象',
    rarity: 'R',
    types: ['lacquer'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L02'],
    oneLiner: '黑红金的色彩搭配，是许多人记住楚漆器的第一眼。',
    coreLore:
      '楚地漆器常见黑地朱纹或红黑对比，并饰金色等，视觉冲击力强。色彩本身就是文化记忆：庄重里带热烈，沉默里带飞扬。',
    source: SRC,
    todayLink: '设计配色时，「楚红楚黑」仍是灵感库。',
    tellable: '楚漆的红，像夜色里忽然亮起的心。',
    restore: quiz(
      '楚漆器给人的常见第一眼印象是？',
      [
        { id: 'a', text: '红黑等强对比与光泽', correct: true },
        { id: 'b', text: '只有透明无色', correct: false },
        { id: 'c', text: '荧光涂鸦必选配色', correct: false },
      ],
      '色彩是记忆点。',
    ),
  },
  {
    id: 'A-R02-N-018',
    name: '屈原印象卡',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L06'],
    oneLiner: '楚辞传统与屈原的名字紧密相连。',
    coreLore:
      '屈原是楚辞传统中最广为人知的诗人形象，作品与忠贞、理想、香草美人等主题相连。本卡只建立文化印象与阅读入口，不代替传记考证全文。',
    source: SRC_LIT,
    todayLink: '端午纪念屈原的习俗与文学记忆，使这个名字仍活在日历里。',
    tellable: '读楚辞，总会先遇见屈原这个名字。',
    restore: quiz(
      '屈原在通识文化里，主要与什么相连？',
      [
        { id: 'a', text: '楚辞传统与相关诗歌形象', correct: true },
        { id: 'b', text: '发明蒸汽机', correct: false },
        { id: 'c', text: '现代球星转会', correct: false },
      ],
      '文学与节日记忆入口。',
    ),
  },
  {
    id: 'A-R02-N-019',
    name: '端午与楚地记忆',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R02',
    learnIds: ['R02-L06'],
    oneLiner: '端午把诗歌、江河与民俗编织在一起。',
    coreLore:
      '端午节俗多样，其中包括与纪念屈原相关的叙事，以及龙舟、粽子等民俗。本展区把它当作「楚地文学记忆如何进入岁时」的例子，尊重各地习俗差异。',
    source: '岁时节日通识与民俗公教。',
    todayLink: '过端午时，可以既吃粽子，也读一句楚辞。',
    tellable: '端午的江上，有鼓声，也有诗。',
    restore: quiz(
      '将端午与楚地联系起来时，较稳妥的说法是？',
      [
        { id: 'a', text: '部分叙事与屈原/楚辞记忆相关，民俗因时因地而异', correct: true },
        { id: 'b', text: '全世界只有一种标准过法', correct: false },
        { id: 'c', text: '端午与任何历史记忆无关', correct: false },
      ],
      '多元民俗，谨慎表述。',
    ),
  },
  {
    id: 'A-R02-SR-020',
    name: '楚地小谱',
    rarity: 'SR',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R02',
    learnIds: ['R02-L01', 'R02-L02', 'R02-L06'],
    oneLiner: '凤、漆、诗、江——带走楚地四字印象。',
    coreLore:
      '楚地展区希望你带走：凤鸟的动势；漆器的温润光色；楚辞的浪漫象征；江汉与舟的生活底色。它与中原的礼乐青铜对照，共同组成更完整的早期中国想象。',
    source: '本区域课程纲要汇总。',
    todayLink: '下次看展，试着问：这件东西更像鼎，还是更像凤？',
    tellable: '楚地这一路，我记住了凤、漆、诗和江。',
    restore: quiz(
      '楚地展区最核心的学习主题更接近？',
      [
        { id: 'a', text: '凤鸟·漆器·楚辞·江汉气质', correct: true },
        { id: 'b', text: '只学中原列鼎制度细节', correct: false },
        { id: 'c', text: '现代编程语言语法', correct: false },
      ],
      '凤漆诗江是本区主轴。',
    ),
  },
];
