import type { LoreCard, QuizOption } from '../core/types';
import {
  BOARD,
  kitGoldMask,
  kitPlankRoad,
  kitSacredTree,
  kitShuJin,
  kitVerticalEyes,
  kitZun,
} from './shapeKits.ts';

/** 巴蜀 R03 · 20 张 · 三星堆意象 / 蜀道 / 织锦（通识再创作） */

function shape(pieces: ReturnType<typeof kitVerticalEyes>): LoreCard['restore'] {
  return { kind: 'shape', board: { ...BOARD }, pieces };
}
function quiz(prompt: string, options: QuizOption[], explain: string): LoreCard['restore'] {
  return { kind: 'quiz', prompt, options, explain };
}

const SRC =
  '中国古代巴蜀与古蜀文明通识；公开考古与博物馆公教表述。本展示为再创作示意，非正式馆藏复制，不声称某一具体未授权文物复刻。';

export const BASHU_ARTIFACTS: LoreCard[] = [
  {
    id: 'A-R03-SR-001',
    name: '纵目面具意象',
    rarity: 'SR',
    types: ['bronze'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L01'],
    oneLiner: '双眼如柱外凸的青铜面像，是古蜀视觉记忆的强符号。',
    coreLore:
      '古蜀遗址出土的青铜面具中，有双眼呈柱状外凸的造型，常被称作「纵目」。它强烈改写了我们对「面孔」的想象，是进入巴蜀展区最难忘的第一眼。本卡为通识再创作意象。',
    source: SRC,
    todayLink: '博物馆里若看到外凸的铜目，不妨停一下：那是另一种「看见世界」的方式。',
    tellable: '纵目像把目光伸得更长——古蜀的脸，从眼里开始传奇。',
    restore: shape(kitVerticalEyes()),
  },
  {
    id: 'A-R03-SR-002',
    name: '黄金面罩意象',
    rarity: 'SR',
    types: ['gold', 'bronze'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L02'],
    oneLiner: '贴覆于面的金箔光泽，是古蜀礼仪视觉的一部分。',
    coreLore:
      '古蜀遗存中出现黄金面罩/金箔覆面等现象，说明贵金属被用于面部礼仪与神性表达。入门记住：金不只是财富，也可以是「给面孔穿上的礼」。',
    source: SRC,
    todayLink: '今天的金，常联想到首饰；在古蜀语境里，它更靠近仪式与神采。',
    tellable: '金面一亮，面孔就从人间走到仪典里。',
    restore: shape(kitGoldMask()),
  },
  {
    id: 'A-R03-N-003',
    name: '巴蜀知一张',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L03'],
    oneLiner: '巴与蜀：西南山地与盆地里的古老文明印象。',
    coreLore:
      '「巴蜀」常并称，指今四川盆地及周边相关的历史地理与文化传统。古蜀文明以独特青铜与金器面貌闻名。本展区用「巴蜀」指这一区域文化气质，而非精确行政区划课。',
    source: '历史地理与区域文化通识。',
    todayLink: '旅行到成都平原，许多博物馆都在讲这条文明支流。',
    tellable: '巴蜀不只是火锅地图，更是纵目与金面的文明记忆。',
    restore: quiz(
      '本展区「巴蜀」主要指？',
      [
        { id: 'a', text: '西南相关的古国/区域文化印象', correct: true },
        { id: 'b', text: '北欧维京专属名词', correct: false },
        { id: 'c', text: '仅指现代一个街道名', correct: false },
      ],
      '文化展区名，服务学习。',
    ),
  },
  {
    id: 'A-R03-R-004',
    name: '青铜神树意象',
    rarity: 'R',
    types: ['bronze'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L01'],
    oneLiner: '枝干伸向天空的铜树，连接神性与工艺。',
    coreLore:
      '古蜀大型青铜神树是极具冲击力的器物类型意象：树、鸟、龙等元素组合，常被解读为沟通天地的象征系统。入门只需感受「树可以铸成青铜的宇宙模型」。',
    source: SRC,
    todayLink: '艺术里的「生命树」主题，在世界许多文明中都能遇见回声。',
    tellable: '神树把天空，接到了青铜的枝头。',
    restore: shape(kitSacredTree()),
  },
  {
    id: 'A-R03-R-005',
    name: '蜀锦一角',
    rarity: 'R',
    types: ['textile'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L04'],
    oneLiner: '经纬交织的彩色纹样，是四川织锦的名片。',
    coreLore:
      '蜀锦是中国传统织锦名品，以多彩经纬织出图案，历史悠久。它提醒我们：巴蜀的文明不只在青铜与金，也在柔软的丝线上。',
    source: '中国传统织锦与蜀锦通识。',
    todayLink: '成都等地仍有蜀锦传统工艺的展示与传承。',
    tellable: '蜀锦是可以披在肩上的山川花纹。',
    restore: shape(kitShuJin()),
  },
  {
    id: 'A-R03-R-006',
    name: '栈道印象',
    rarity: 'R',
    types: ['folk', 'concept'],
    authTag: 'folk',
    region: 'R03',
    learnIds: ['R03-L05'],
    oneLiner: '崖壁上的木梁之路，是山地交通的勇敢发明。',
    coreLore:
      '栈道是在陡峭山崖上架木成路的交通方式，与蜀道艰难的历史记忆相连。它解释了「蜀道之难」不只是诗句，也是地理与工程的真实挑战。',
    source: '历史交通与民俗地理通识。',
    todayLink: '现代公路隧道改变了速度，但山势仍在。',
    tellable: '栈道是把路，钉在悬崖上的勇气。',
    restore: shape(kitPlankRoad()),
  },
  {
    id: 'A-R03-N-007',
    name: '蜀道难',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L05'],
    oneLiner: '诗句把地理的险，变成可以传诵的文化记忆。',
    coreLore:
      '「蜀道之难，难于上青天」等诗句，使巴蜀山路进入中国人的集体语言。文学不是工程报告，却能让地理被记住、被共情。',
    source: '古典诗歌通识（李白等相关名篇的公共记忆）。',
    todayLink: '当我们说某事「难于上青天」，仍在借用这条蜀道隐喻。',
    tellable: '蜀道先难在山，后难在诗——诗让难变得不朽。',
    restore: quiz(
      '「蜀道难」作为文化记忆，主要帮助我们理解？',
      [
        { id: 'a', text: '巴蜀山地交通之险与诗意表达', correct: true },
        { id: 'b', text: '海平面航运规则', correct: false },
        { id: 'c', text: '现代地铁时刻表', correct: false },
      ],
      '诗与地理互证。',
    ),
  },
  {
    id: 'A-R03-N-008',
    name: '三星堆印象',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L03'],
    oneLiner: '一处让世界重新打量古蜀的名字。',
    coreLore:
      '三星堆是古蜀文明最广为人知的遗址名称之一，出土器物造型独特，引发持续的公众兴趣与学术讨论。本展区借其公共知名度作入口，细节以公开资料与博物馆为准。',
    source: SRC,
    todayLink: '想深入，请走博物馆与正规考古发布，而不是传闻短视频。',
    tellable: '三星堆三个字，像一把钥匙，打开古蜀的奇异门。',
    restore: quiz(
      '了解三星堆较稳妥的方式是？',
      [
        { id: 'a', text: '参考博物馆与公开考古资料', correct: true },
        { id: 'b', text: '只信夸张谣言', correct: false },
        { id: 'c', text: '完全不看任何资料', correct: false },
      ],
      '公共知识要可核对。',
    ),
  },
  {
    id: 'A-R03-N-009',
    name: '金与铜的搭配',
    rarity: 'N',
    types: ['concept', 'craft'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L02'],
    oneLiner: '贵金属与青铜可以一起讲礼仪故事。',
    coreLore:
      '古蜀遗存中金器与青铜器并出的现象，说明不同材料在礼仪系统中分工合作：铜可塑巨大神性形象，金可赋予面孔特殊光泽。材料组合本身就是文化信息。',
    source: SRC,
    todayLink: '设计里的「材质对比」，古人早已用在仪典上。',
    tellable: '铜铸体量，金点眼神——古蜀很懂材料的戏剧。',
    restore: quiz(
      '金与铜在古蜀礼仪语境中，更合适的理解是？',
      [
        { id: 'a', text: '不同材料可共同服务礼仪表达', correct: true },
        { id: 'b', text: '只能二选一、互相消灭', correct: false },
        { id: 'c', text: '与任何仪式无关', correct: false },
      ],
      '组合即信息。',
    ),
  },
  {
    id: 'A-R03-R-010',
    name: '青铜立人意象',
    rarity: 'R',
    types: ['bronze'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L01'],
    oneLiner: '双手持物的高大铜人，像在完成一场永恒的仪式。',
    coreLore:
      '古蜀青铜立人像以尺度与手势著称，常被理解为与祭祀相关的形象。入门记住：人像也可以铸得巨大，用来「站进」礼仪空间。',
    source: SRC,
    todayLink: '看展时注意手的姿势——手势常常在说话。',
    tellable: '立人举起的不是哑铃，是仪式的时间。',
    restore: shape(kitZun()),
  },
  {
    id: 'A-R03-N-011',
    name: '盆地与山脉',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L03'],
    oneLiner: '平原孕育聚落，山脉塑造道路与想象。',
    coreLore:
      '四川盆地提供农耕与聚落条件，四周山脉既是屏障也是通道挑战。地理帮助我们理解：为何这里发展出独特面貌，又与外界保持交流。',
    source: '历史地理通识。',
    todayLink: '高铁穿越群山，是当代人对「蜀道」的回答。',
    tellable: '巴蜀的故事，写在盆地的肚子里，也写在山的褶皱上。',
    restore: quiz(
      '理解巴蜀文明独特性，较有帮助的背景是？',
      [
        { id: 'a', text: '盆地与山地的地理格局', correct: true },
        { id: 'b', text: '完全平坦的无边沙漠', correct: false },
        { id: 'c', text: '北极冰盖专属环境', correct: false },
      ],
      '地理是背景，不是唯一原因。',
    ),
  },
  {
    id: 'A-R03-N-012',
    name: '盐与交通',
    rarity: 'N',
    types: ['concept', 'folk'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L05'],
    oneLiner: '盐等资源，推动路与人的往来。',
    coreLore:
      '包括井盐在内的资源，在西南历史中影响生计与交通网络。资源—道路—聚落，是理解区域文明的实用框架（本卡点到为止）。',
    source: '区域经济史通识。',
    todayLink: '「盐」进入日常菜肴前，也曾是路上的重量。',
    tellable: '有些路，是盐的味道走出来的。',
    restore: quiz(
      '资源与道路的关系，更接近？',
      [
        { id: 'a', text: '重要资源常推动交通与交往', correct: true },
        { id: 'b', text: '资源从不影响人类走动', correct: false },
        { id: 'c', text: '道路只为游戏积分存在', correct: false },
      ],
      '生计塑造空间。',
    ),
  },
  {
    id: 'A-R03-N-013',
    name: '想象与证据',
    rarity: 'N',
    types: ['concept', 'ethics'],
    authTag: 'public_edu',
    region: 'R03',
    learnIds: ['R03-L06', 'R03-X-ethics'],
    oneLiner: '古蜀很神奇，但解释要守证据。',
    coreLore:
      '公众对古蜀充满好奇，网络上也有许多夸张假说。健康态度是：允许审美震撼与合理推测，但把「已证实」与「假说」分开，尊重考古地层与报告。',
    source: '科学素养与公共考古倡导。',
    todayLink: '神奇吸引目光，证据保护真相。',
    tellable: '我愿被纵目震撼，也愿等考古说话。',
    restore: quiz(
      '面对古蜀相关奇闻，更合适的是？',
      [
        { id: 'a', text: '区分证据与假说，优先权威发布', correct: true },
        { id: 'b', text: '越离奇越全信', correct: false },
        { id: 'c', text: '拒绝一切公开资料', correct: false },
      ],
      '好奇心 + 证据意识。',
    ),
  },
  {
    id: 'A-R03-R-014',
    name: '太阳轮意象',
    rarity: 'R',
    types: ['bronze', 'pattern'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L01'],
    oneLiner: '圆环放射的铜纹，像把日光铸进器物。',
    coreLore:
      '古蜀器物中有轮状、放射状装饰母题，常引发与太阳崇拜相关的讨论。入门阶段把它记为「圆形放射的神性图案」即可，具体含义以研究进展为准。',
    source: SRC,
    todayLink: '人类许多文明都用圆与光表达时间与神圣。',
    tellable: '太阳可以不用升起——铜也能圆圆地亮。',
    restore: quiz(
      '「太阳轮」类图案，入门时更该先？',
      [
        { id: 'a', text: '记住形态：圆与放射', correct: true },
        { id: 'b', text: '立刻写成最终科学定论', correct: false },
        { id: 'c', text: '认定与任何文化无关', correct: false },
      ],
      '先形态，后解释。',
    ),
  },
  {
    id: 'A-R03-N-015',
    name: '与中原交流',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L03'],
    oneLiner: '独特不等于隔绝。',
    coreLore:
      '古蜀面貌独特，同时也存在与周边及更广阔地区的文化交流迹象。理解文明，要同时看见「自己的脸」和「别人的路」。',
    source: '考古学文化交流通识。',
    todayLink: '今天的四川，仍是开放与地方性并存。',
    tellable: '纵目看向远方，远方也有回声。',
    restore: quiz(
      '关于古蜀与外部世界，更稳妥的是？',
      [
        { id: 'a', text: '既有独特性，也可能有交流', correct: true },
        { id: 'b', text: '绝对从未与外界往来', correct: false },
        { id: 'c', text: '只是中原的完全复制粘贴', correct: false },
      ],
      '独特与交流可并存。',
    ),
  },
  {
    id: 'A-R03-N-016',
    name: '大熊猫不是古蜀青铜',
    rarity: 'N',
    types: ['concept', 'public_edu'],
    authTag: 'public_edu',
    region: 'R03',
    learnIds: ['R03-X-ethics'],
    oneLiner: '现生动物名片 ≠ 直接等同某件青铜神器。',
    coreLore:
      '大熊猫是当代四川的生态与文化名片，但学习古蜀青铜时应避免把一切都「可爱化」或错误等同。分清自然遗产与考古遗存，两者都珍贵，却不是同一门课。',
    source: '公共教育概念澄清。',
    todayLink: '可以又爱熊猫，又认真读考古。',
    tellable: '熊猫管今天的萌，纵目管昨天的神——都重要。',
    restore: quiz(
      '学习古蜀文物时，更合适的是？',
      [
        { id: 'a', text: '区分自然名片与考古遗存', correct: true },
        { id: 'b', text: '把所有文物都说成熊猫造型', correct: false },
        { id: 'c', text: '否认四川有任何现代生态价值', correct: false },
      ],
      '分类清晰，尊重双方。',
    ),
  },
  {
    id: 'A-R03-R-017',
    name: '玉璋印象',
    rarity: 'R',
    types: ['jade'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L02'],
    oneLiner: '长条瑞玉也在西南礼仪世界中出现。',
    coreLore:
      '玉璋等瑞玉在包括古蜀在内的礼仪系统中具有重要性。与中原玉器传统对照，可见玉作为「礼的材料」在广域内的共鸣。',
    source: SRC,
    todayLink: '玉的温润，跨越许多区域的审美。',
    tellable: '玉在巴蜀，同样会说话——只是口音不同。',
    restore: quiz(
      '玉璋一类器物，通识上更接近？',
      [
        { id: 'a', text: '礼仪/瑞信相关的玉器类型', correct: true },
        { id: 'b', text: '现代不锈钢餐具', correct: false },
        { id: 'c', text: '塑料玩具默认材质', correct: false },
      ],
      '玉与礼相关。',
    ),
  },
  {
    id: 'A-R03-N-018',
    name: '看展：先震撼后提问',
    rarity: 'N',
    types: ['concept'],
    authTag: 'public_edu',
    region: 'R03',
    learnIds: ['R03-X-museum'],
    oneLiner: '允许心跳加速，然后问：这是什么？为何这样？',
    coreLore:
      '面对古蜀器物，震撼是正常的。好的参观是：先感受，再读说明牌，再把「我不知道」变成具体问题。本游戏的文化卡，就是训练这种节奏。',
    source: '博物馆公教方法。',
    todayLink: '震撼之后，说明牌是最好的朋友。',
    tellable: '我先被镇住，再被知识轻轻扶起。',
    restore: quiz(
      '看古蜀大展，较推荐的节奏是？',
      [
        { id: 'a', text: '感受 → 读说明 → 形成问题', correct: true },
        { id: 'b', text: '只自拍不看展品', correct: false },
        { id: 'c', text: '否定一切说明牌', correct: false },
      ],
      '感受与阅读并重。',
    ),
  },
  {
    id: 'A-R03-N-019',
    name: '方言与地名余韵',
    rarity: 'N',
    types: ['folk', 'concept'],
    authTag: 'folk',
    region: 'R03',
    learnIds: ['R03-L03'],
    oneLiner: '活着的口语与地名，也是区域文化的线索。',
    coreLore:
      '巴蜀方言与地名保留了历史层积。它们不直接等于考古结论，却让人感到文明仍在日常生活里呼吸。学习时把「活态」与「出土」互相参照即可。',
    source: '方言与地名文化通识。',
    todayLink: '点一道川菜、听一句方言，也是轻量的文化接触。',
    tellable: '有的历史，藏在口音的曲折里。',
    restore: quiz(
      '方言地名对理解区域文化的价值是？',
      [
        { id: 'a', text: '提供活态线索，需与史料对照', correct: true },
        { id: 'b', text: '可以替代全部考古报告', correct: false },
        { id: 'c', text: '完全没有文化意义', correct: false },
      ],
      '活态线索，谨慎使用。',
    ),
  },
  {
    id: 'A-R03-SR-020',
    name: '巴蜀小谱',
    rarity: 'SR',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R03',
    learnIds: ['R03-L01', 'R03-L02', 'R03-L05'],
    oneLiner: '纵目、金面、神树、蜀道——带走巴蜀四印象。',
    coreLore:
      '巴蜀展区希望你带走：纵目的奇异面孔；黄金的礼仪光泽；神树的宇宙想象；蜀道与栈道的地理勇气，以及蜀锦的柔软文明。它与中原、楚地并列，使早期中国更立体。',
    source: '本区域课程纲要汇总。',
    todayLink: '下次看展，问自己：这更像鼎、像凤，还是像纵目？',
    tellable: '巴蜀这一路，我记住了眼睛、金子、树和山路。',
    restore: quiz(
      '巴蜀展区最核心的学习主题更接近？',
      [
        { id: 'a', text: '古蜀奇器·金铜礼仪·蜀道与织锦', correct: true },
        { id: 'b', text: '只学江南园林漏窗', correct: false },
        { id: 'c', text: '现代芯片制程参数', correct: false },
      ],
      '纵目金树与蜀道是主轴。',
    ),
  },
];
