import type { LoreCard, QuizOption } from '../core/types';
import {
  BOARD,
  kitBlueWhite,
  kitFan,
  kitGardenCorner,
  kitPorcelainVase,
  kitScroll,
  kitTeacup,
} from './shapeKits.ts';

/** 江南 R04 · 20 张 · 瓷、园、雅集、丝与月（通识再创作） */

function shape(pieces: ReturnType<typeof kitPorcelainVase>): LoreCard['restore'] {
  return { kind: 'shape', board: { ...BOARD }, pieces };
}
function quiz(prompt: string, options: QuizOption[], explain: string): LoreCard['restore'] {
  return { kind: 'quiz', prompt, options, explain };
}

const SRC =
  '中国古代江南地区工艺、园林与文人生活通识；公开博物馆与文化读本。本展示为再创作示意，非正式馆藏复制。';

export const JIANGNAN_ARTIFACTS: LoreCard[] = [
  {
    id: 'A-R04-SR-001',
    name: '青白瓷瓶',
    rarity: 'SR',
    types: ['ceramic'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L01'],
    oneLiner: '温润如玉的瓷光，是江南窑火给人的第一封信。',
    coreLore:
      '瓷器是中国对世界物质文化的重要贡献。江南及周边窑系以青白、青瓷等闻名，釉色追求温润。认识瓷，是理解「土与火如何变成半透明文明」的入口。',
    source: SRC,
    todayLink: '餐桌上的瓷，仍连接着千年前的窑温。',
    tellable: '瓷光一亮，泥土就学会了谦逊的发光。',
    restore: shape(kitPorcelainVase()),
  },
  {
    id: 'A-R04-R-002',
    name: '青花一笔',
    rarity: 'R',
    types: ['ceramic', 'pattern'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L01'],
    oneLiner: '白地蓝花，是许多人认出「中国瓷」的颜色。',
    coreLore:
      '青花以钴料在瓷坯上绘制再施透明釉烧成，蓝白对比清爽。它在元明以来广为流传，成为中国瓷器最易辨认的公共面孔之一。',
    source: SRC,
    todayLink: '设计里的蓝白，常常在向瓷器致意。',
    tellable: '青花是瓷器写给世界的一封蓝色短信。',
    restore: shape(kitBlueWhite()),
  },
  {
    id: 'A-R04-N-003',
    name: '江南知一张',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L02'],
    oneLiner: '江南：水网、市镇与雅致生活的文化地理。',
    coreLore:
      '「江南」在不同时代范围有别，常与长江下游水乡、市镇繁荣与文人趣味相连。本展区用它指一种温润、细密、重工艺与园林的文化气质。',
    source: '历史地理与文化通识。',
    todayLink: '烟雨、小桥、茶香，仍是江南的公共想象。',
    tellable: '江南不是一个点，是一片被水写柔的气质。',
    restore: quiz(
      '本展区「江南」主要用来指？',
      [
        { id: 'a', text: '水乡市镇与雅致工艺的文化气质', correct: true },
        { id: 'b', text: '沙漠绿洲专有名词', correct: false },
        { id: 'c', text: '只有极地科考站', correct: false },
      ],
      '文化气质，非精确测绘。',
    ),
  },
  {
    id: 'A-R04-SR-004',
    name: '园林一角',
    rarity: 'SR',
    types: ['garden'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L03'],
    oneLiner: '粉墙漏窗与湖石，把自然轻轻请入宅院。',
    coreLore:
      '江南私家园林以有限空间营造山水意境，常用粉墙、漏窗、湖石、池水与花木。它是「可游可居的山水画」，体现文人的空间美学。',
    source: SRC,
    todayLink: '苏州等地古典园林是世界遗产，也是公共游览地。',
    tellable: '园林是把山水，折叠进墙里的智慧。',
    restore: shape(kitGardenCorner()),
  },
  {
    id: 'A-R04-R-005',
    name: '折扇',
    rarity: 'R',
    types: ['craft'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L04'],
    oneLiner: '开合之间，风与书画一同到来。',
    coreLore:
      '折扇在中国文人生活中既实用又是书画载体，扇面可写可画。它连接手的温度与纸的艺术，是雅集生活的小道具。',
    source: SRC,
    todayLink: '今天的扇，仍可是夏日与设计的接口。',
    tellable: '扇子一展，半幅书画就有了风。',
    restore: shape(kitFan()),
  },
  {
    id: 'A-R04-R-006',
    name: '茶盏',
    rarity: 'R',
    types: ['ceramic'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L05'],
    oneLiner: '一杯在手，市井与雅事之间只有一盏之隔。',
    coreLore:
      '茶盏是饮茶的核心器物，造型与釉色影响观汤与手感。江南茶风与瓷器工艺相互成就，使「喝茶」成为可审美的日常。',
    source: SRC,
    todayLink: '办公室的一杯茶，仍可有一点仪式感。',
    tellable: '茶盏不大，却装得下慢下来的午后。',
    restore: shape(kitTeacup()),
  },
  {
    id: 'A-R04-N-007',
    name: '文人雅集',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L04'],
    oneLiner: '以文会友：诗、书、画、茶可以在同一张桌子上。',
    coreLore:
      '雅集是文人聚会的文化形式，常包含诗文唱和、书画鉴赏与茶酒。它不是炫富派对，而是以共同教养为纽带的社交美学——理解江南气质的一把钥匙。',
    source: SRC,
    todayLink: '今天的读书会、茶会，仍有雅集的淡淡回声。',
    tellable: '雅集是把朋友，约进诗和茶里。',
    restore: quiz(
      '文人雅集更核心的内容接近？',
      [
        { id: 'a', text: '诗文书画与清谈品鉴', correct: true },
        { id: 'b', text: '纯电竞排名赛', correct: false },
        { id: 'c', text: '强制推销课程', correct: false },
      ],
      '以文会友。',
    ),
  },
  {
    id: 'A-R04-R-008',
    name: '绢本卷轴意象',
    rarity: 'R',
    types: ['painting', 'textile'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L04'],
    oneLiner: '打开一幅画，像打开一段可徐徐展开的时间。',
    coreLore:
      '中国书画常以卷轴形式装裱与观赏，阅读是移动的、有节奏的。江南文人传统中，书画是核心教养。本卡建立「卷轴观看」的印象。',
    source: SRC,
    todayLink: '博物馆书画展的「慢慢展卷」，本身就是礼仪。',
    tellable: '卷轴不急着一眼看完——它教人走路的眼睛。',
    restore: shape(kitScroll()),
  },
  {
    id: 'A-R04-N-009',
    name: '窑火与分工',
    rarity: 'N',
    types: ['concept', 'craft'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L01'],
    oneLiner: '一只瓷，经过泥土、拉坯、上釉与火。',
    coreLore:
      '传统制瓷包含炼泥、成型、装饰、上釉、装烧等多环节，常有精细分工。理解「瓷是火的作品」，能更敬重博物馆橱窗里那一层安静的光。',
    source: SRC,
    todayLink: '现代工业瓷与手工瓷路径不同，都值得尊重。',
    tellable: '瓷的温柔，是火给过它严厉的考试。',
    restore: quiz(
      '传统制瓷过程，更接近？',
      [
        { id: 'a', text: '多道工序，经火烧成', correct: true },
        { id: 'b', text: '冰块自然凝结', correct: false },
        { id: 'c', text: '纯印刷油墨风干', correct: false },
      ],
      '土与火。',
    ),
  },
  {
    id: 'A-R04-N-010',
    name: '丝与绣',
    rarity: 'N',
    types: ['textile', 'concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L06'],
    oneLiner: '江南的柔，有一半写在丝线上。',
    coreLore:
      '丝绸与刺绣是江南重要的物质文化。它们既是衣被日用，也是礼仪、商贸与艺术的载体。与巴蜀蜀锦对照，可见中国织绣传统的多中心。',
    source: SRC,
    todayLink: '非遗绣种与现代时装仍在对话。',
    tellable: '丝线细，却能绣出很大的世界。',
    restore: quiz(
      '丝绸刺绣在江南文化中的位置，更接近？',
      [
        { id: 'a', text: '日用与艺术兼具的重要传统', correct: true },
        { id: 'b', text: '与江南完全无关', correct: false },
        { id: 'c', text: '只存在于科幻电影', correct: false },
      ],
      '柔的文明力量。',
    ),
  },
  {
    id: 'A-R04-N-011',
    name: '月色与水',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L02'],
    oneLiner: '诗词里的江南，常被月光与波光一起写亮。',
    coreLore:
      '古典诗词中，江南常与月光、水面、小船、思念相连。文学塑造了人们对江南的情感滤镜——真实地理与诗意地理叠合，才是完整的「江南」。',
    source: '古典文学通识。',
    todayLink: '中秋或雨夜读一句江南诗，气质会轻轻靠近。',
    tellable: '江南的月亮，好像特别会加水。',
    restore: quiz(
      '古典诗词中的江南，常借助哪些意象？',
      [
        { id: 'a', text: '月、水、船与柔情等', correct: true },
        { id: 'b', text: '只有沙漠风暴', correct: false },
        { id: 'c', text: '只有工厂管道', correct: false },
      ],
      '诗意滤镜。',
    ),
  },
  {
    id: 'A-R04-N-012',
    name: '市镇与商贸',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L02'],
    oneLiner: '桥边的市声，也是文明的一种节奏。',
    coreLore:
      '明清以来江南市镇繁荣，丝棉、粮食与手工业推动市井生活。雅致园林与热闹市镇可以并存：理解江南，不要只看见园林的静。',
    source: '社会经济史通识。',
    todayLink: '古镇旅游火热，也请尊重居民的日常。',
    tellable: '江南既有琴声，也有卖藕的声音。',
    restore: quiz(
      '全面理解江南，更合适的是？',
      [
        { id: 'a', text: '雅致与市井都看见', correct: true },
        { id: 'b', text: '只承认园林、否认市镇', correct: false },
        { id: 'c', text: '只承认工厂、否认文化', correct: false },
      ],
      '静与闹的统一。',
    ),
  },
  {
    id: 'A-R04-N-013',
    name: '对照：鼎与瓷',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L01'],
    oneLiner: '青铜的礼与瓷器的日用雅致，都是中国。',
    coreLore:
      '中原青铜礼器强调秩序与祭祀；江南瓷器传统更贴近日用审美与文人趣味。对照不是取代，而是让文明时间线更长、更丰。',
    source: '物质文化比较通识。',
    todayLink: '博物馆里从青铜馆走到瓷器馆，就是一场时间旅行。',
    tellable: '鼎教人庄重，瓷教人把庄重过成生活。',
    restore: quiz(
      '鼎与瓷的对照，更合适的理解是？',
      [
        { id: 'a', text: '不同时代气质与功能的互补', correct: true },
        { id: 'b', text: '必须二选一消灭', correct: false },
        { id: 'c', text: '毫无关系的两样东西', correct: false },
      ],
      '互补的中国。',
    ),
  },
  {
    id: 'A-R04-N-014',
    name: '园林不是盆景全部',
    rarity: 'N',
    types: ['garden', 'concept'],
    authTag: 'public_edu',
    region: 'R04',
    learnIds: ['R04-X-ethics', 'R04-L03'],
    oneLiner: '游园请尊重花木与规矩，别只剩打卡。',
    coreLore:
      '古典园林是文化遗产，也是需要保护的公共空间。欣赏漏窗借景的同时，遵守参观秩序，不攀折损伤，是「雅」的当代版本。',
    source: '文保与公教倡导。',
    todayLink: '真正的风雅，包含对公共之物的克制。',
    tellable: '游园的最高级，是把脚印放轻。',
    restore: quiz(
      '参观古典园林，更合适的是？',
      [
        { id: 'a', text: '欣赏并遵守保护与秩序', correct: true },
        { id: 'b', text: '攀折花木只为拍照', correct: false },
        { id: 'c', text: '大声破坏安静氛围为乐', correct: false },
      ],
      '风雅含公德。',
    ),
  },
  {
    id: 'A-R04-R-015',
    name: '紫砂印象',
    rarity: 'R',
    types: ['ceramic'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L05'],
    oneLiner: '不施釉的紫砂，以泥料与造型说话。',
    coreLore:
      '宜兴紫砂以特殊泥料制壶，常不施釉，强调泥色与器形。它与江南茶书传统深度绑定，是「手作温度」的代表之一。',
    source: SRC,
    todayLink: '一把好壶，养的是时间。',
    tellable: '紫砂不靠釉亮，靠的是被手握过的诚意。',
    restore: quiz(
      '紫砂壶常见特点是？',
      [
        { id: 'a', text: '多用特有泥料，常不施釉', correct: true },
        { id: 'b', text: '必须透明如玻璃', correct: false },
        { id: 'c', text: '只能是塑料材质', correct: false },
      ],
      '泥与手。',
    ),
  },
  {
    id: 'A-R04-N-016',
    name: '书画四事印象',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L04'],
    oneLiner: '笔墨纸砚，是文人书桌上的基本装备。',
    coreLore:
      '笔、墨、纸、砚合称「文房四宝」，是中国书画的物质基础。江南文人传统使这些物件既是工具，也是品鉴对象。',
    source: SRC,
    todayLink: '即使触屏写字，理解纸笔仍有助于理解古典美学。',
    tellable: '四宝不是宝物柜，是能写出山河的四件伙伴。',
    restore: quiz(
      '「文房四宝」通常指？',
      [
        { id: 'a', text: '笔墨纸砚', correct: true },
        { id: 'b', text: '锅碗瓢盆', correct: false },
        { id: 'c', text: '琴棋只含电子琴', correct: false },
      ],
      '书桌上的文明。',
    ),
  },
  {
    id: 'A-R04-N-017',
    name: '烟雨气质',
    rarity: 'N',
    types: ['concept', 'folk'],
    authTag: 'folk',
    region: 'R04',
    learnIds: ['R04-L02'],
    oneLiner: '潮湿的空气，也参与了审美。',
    coreLore:
      '江南多雨湿润，影响建筑出檐、生活方式与文艺气质。气候不是决定论，却是理解粉墙黛瓦与柔美文风的背景板。',
    source: '区域文化与气候通识。',
    todayLink: '带把伞走江南，既是实用，也是仪式。',
    tellable: '江南的雨，会把声音也打湿一点。',
    restore: quiz(
      '理解江南粉墙黛瓦，有帮助的背景是？',
      [
        { id: 'a', text: '多雨湿润等区域环境与生活', correct: true },
        { id: 'b', text: '全年无降水的极旱沙漠', correct: false },
        { id: 'c', text: '与气候完全无关的随机涂色', correct: false },
      ],
      '环境参与审美。',
    ),
  },
  {
    id: 'A-R04-N-018',
    name: '工艺传承',
    rarity: 'N',
    types: ['craft', 'public_edu'],
    authTag: 'public_edu',
    region: 'R04',
    learnIds: ['R04-L06'],
    oneLiner: '手艺活在人的手上，也活在尊重里。',
    coreLore:
      '瓷、绣、扇、园等传统需要传承人与制度支持。作为观众，购买正规文创、尊重知识产权、传播准确知识，都是轻量的支持方式。',
    source: '非遗保护公共倡导。',
    todayLink: '喜欢就好好学、好好说，比跟风贬低更有用。',
    tellable: '手艺的未来，有一半在观众的态度里。',
    restore: quiz(
      '支持传统工艺，较合适的是？',
      [
        { id: 'a', text: '尊重传承、正规消费与准确传播', correct: true },
        { id: 'b', text: '盗版仿冒并嘲笑匠人', correct: false },
        { id: 'c', text: '要求所有手艺立刻消失', correct: false },
      ],
      '尊重即支持。',
    ),
  },
  {
    id: 'A-R04-N-019',
    name: '四区对照小结',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L02'],
    oneLiner: '鼎、凤、纵目、瓷——四张不同的中国脸。',
    coreLore:
      '中原礼乐青铜、楚地凤漆诗、巴蜀奇器蜀道、江南瓷园雅集：四条路线不是考试大纲，而是帮你建立「中国很大、很丰富」的身体记忆。',
    source: '本游戏展区课程汇总。',
    todayLink: '你可以有一个最爱，但请给其他脸孔留位置。',
    tellable: '我走了四条路，才敢说自己见过一点中国。',
    restore: quiz(
      '本游戏多展区设计的主要目的是？',
      [
        { id: 'a', text: '呈现多元文化气质，便于对照学习', correct: true },
        { id: 'b', text: '证明只有一个地区有文化', correct: false },
        { id: 'c', text: '强制付费解锁地图', correct: false },
      ],
      '多元并置。',
    ),
  },
  {
    id: 'A-R04-SR-020',
    name: '江南小谱',
    rarity: 'SR',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R04',
    learnIds: ['R04-L01', 'R04-L03', 'R04-L05'],
    oneLiner: '瓷、园、扇、茶——带走江南四字温柔。',
    coreLore:
      '江南展区希望你带走：瓷器的土与火；园林的咫尺山水；雅集与书画的生活美学；茶盏里的日常仪式，以及丝与绣的柔软力量。',
    source: '本区域课程纲要汇总。',
    todayLink: '下一场雨里，记得江南不只是滤镜，也是手艺与秩序。',
    tellable: '江南这一路，我记住了瓷光、粉墙、扇骨和茶香。',
    restore: quiz(
      '江南展区最核心的学习主题更接近？',
      [
        { id: 'a', text: '瓷器·园林·雅集·茶丝', correct: true },
        { id: 'b', text: '只学纵目面具造型细节', correct: false },
        { id: 'c', text: '现代汽车发动机拆解', correct: false },
      ],
      '瓷园雅茶是主轴。',
    ),
  },
];
