import type { LoreCard, QuizOption } from '../core/types';
import {
  BOARD,
  kitClassicPage,
  kitImmortalPeak,
  kitMythRiver,
  kitNineTail,
  kitPhoenix,
} from './shapeKits.ts';

/** 仙山 R06 · 20 张 · 《山海经》地理与异兽想象（经载再创作） */

function shape(pieces: ReturnType<typeof kitImmortalPeak>): LoreCard['restore'] {
  return { kind: 'shape', board: { ...BOARD }, pieces };
}
function quiz(prompt: string, options: QuizOption[], explain: string): LoreCard['restore'] {
  return { kind: 'quiz', prompt, options, explain };
}

const SRC = '《山海经》及通行注本、文学史通识。本展区为典籍想象的艺术再创作，不作现代地理实测。';

export const XIANSHAN_ARTIFACTS: LoreCard[] = [
  {
    id: 'A-R06-SR-001',
    name: '昆仑意象',
    rarity: 'SR',
    types: ['classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L01'],
    oneLiner: '群山与神性居所的经典坐标。',
    coreLore:
      '昆仑在《山海经》等典籍与后世想象中，常被写成崇高、神异的山系坐标。它不必对应某一现代山峰唯一答案，却深刻影响了中国人的「仙山」观念。',
    source: SRC,
    todayLink: '国风创作里的「昆仑」，仍是神性空间的快捷键。',
    tellable: '昆仑是山，也是想象力的海拔。',
    restore: shape(kitImmortalPeak()),
  },
  {
    id: 'A-R06-R-002',
    name: '九尾狐印象',
    rarity: 'R',
    types: ['classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L02'],
    oneLiner: '多尾之狐，是经载异兽里最广为人知的面孔之一。',
    coreLore:
      '九尾狐见于《山海经》等记载与后世演变，形象随时代变化。本卡建立「经载异兽可以被反复再创作」的印象，不绑定单一善恶定论。',
    source: SRC,
    todayLink: '当代影视与游戏中的狐仙，多有古典源头。',
    tellable: '九尾不是时尚配件，是一条很长的故事尾巴。',
    restore: shape(kitNineTail()),
  },
  {
    id: 'A-R06-N-003',
    name: '仙山知一张',
    rarity: 'N',
    types: ['concept', 'classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L03'],
    oneLiner: '本展区：把《山海经》的奇想读成可参观的想象地图。',
    coreLore:
      '仙山展区对应典籍地理与异兽想象，强调「经载 / 再创作」标签。它与中原史证器物对照：一边是可核验的礼器，一边是滋养艺术的神话土壤。',
    source: SRC,
    todayLink: '读神话，是为了理解文化，不是替代科学。',
    tellable: '仙山是书架上的远方，不是 GPS 目的地。',
    restore: quiz(
      '仙山展区更合适的定位是？',
      [
        { id: 'a', text: '典籍想象与艺术再创作的学习区', correct: true },
        { id: 'b', text: '现代登山强制路线', correct: false },
        { id: 'c', text: '否定一切神话阅读', correct: false },
      ],
      '经载想象区。',
    ),
  },
  {
    id: 'A-R06-R-004',
    name: '山海册残页',
    rarity: 'R',
    types: ['classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L03'],
    oneLiner: '一页经文，像一张会生长的地图。',
    coreLore:
      '《山海经》混有山川、物产、神怪与部族传闻，体例独特。把它当作「博物 + 奇闻」的古典文本来读，比硬套现代学科分类更贴切。',
    source: SRC,
    todayLink: '想深入可读通行注本，而不是只看二创截图。',
    tellable: '山海经是古代的「奇闻数据库」。',
    restore: shape(kitClassicPage()),
  },
  {
    id: 'A-R06-R-005',
    name: '弱水意象',
    rarity: 'R',
    types: ['classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L01'],
    oneLiner: '连羽毛也浮不起的传说之水。',
    coreLore:
      '弱水是典籍中的神异水域意象，常与「不可渡」的险远相连。它展示神话如何用夸张解释地理的隔绝与敬畏。',
    source: SRC,
    todayLink: '文学里的「过不去的水」，往往在说勇气与界限。',
    tellable: '弱水教人：有的边界，用想象来守护。',
    restore: shape(kitMythRiver()),
  },
  {
    id: 'A-R06-R-006',
    name: '鸾鸟/神鸟印象',
    rarity: 'R',
    types: ['classic', 'pattern'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L02'],
    oneLiner: '神鸟在经文与纹样之间飞来飞去。',
    coreLore:
      '《山海经》记载多种神鸟，后世艺术常与凤鸟系统合流或并列。辨认「神鸟」母题，有助于读懂国风设计的翅膀从哪来。',
    source: SRC,
    todayLink: '可与楚地凤鸟展区对照：一地之风，一经之鸟。',
    tellable: '经里的鸟，不一定会叫，但一定会被画。',
    restore: shape(kitPhoenix()),
  },
  {
    id: 'A-R06-N-007',
    name: '经载与史证',
    rarity: 'N',
    types: ['concept'],
    authTag: 'public_edu',
    region: 'R06',
    learnIds: ['R06-L04'],
    oneLiner: '角标提醒你：这是文献想象，还是可核验的物。',
    coreLore:
      '本游戏用「史证·再创作 / 经载 / 民俗 / 岁时」区分知识性质。仙山多为经载：精彩，但勿与出土礼器的证据层级混为一谈。',
    source: '本游戏知识标注原则。',
    todayLink: '阅读任何国风内容，先看它声称的是史还是诗。',
    tellable: '神话很美，标签让美更诚实。',
    restore: quiz(
      '《山海经》异兽卡在本游戏中通常标为？',
      [
        { id: 'a', text: '经载（典籍想象/再创作）', correct: true },
        { id: 'b', text: '现代实验室报告', correct: false },
        { id: 'c', text: '实时卫星测绘', correct: false },
      ],
      '经载标签。',
    ),
  },
  {
    id: 'A-R06-N-008',
    name: '博物传统',
    rarity: 'N',
    types: ['concept', 'classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L03'],
    oneLiner: '把远方的物与名，一页页收进册子。',
    coreLore:
      '《山海经》体现一种古典博物兴趣：记录、命名、分类（以当时方式）。它与后来的地志、笔记小说传统也有呼应。',
    source: SRC,
    todayLink: '自然笔记与观鸟App，是现代的博物冲动。',
    tellable: '博物是对世界保持好奇的古老礼貌。',
    restore: quiz(
      '把《山海经》理解为「博物+奇闻」文本，是否贴切？',
      [
        { id: 'a', text: '较贴切，作为入门视角', correct: true },
        { id: 'b', text: '完全错误，它只是菜谱', correct: false },
        { id: 'c', text: '它禁止记录任何物名', correct: false },
      ],
      '入门视角。',
    ),
  },
  {
    id: 'A-R06-N-009',
    name: '西王母印象',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L01'],
    oneLiner: '昆仑叙事里常出现的神性人物坐标。',
    coreLore:
      '西王母形象在《山海经》与后世文学中演变丰富。本卡只建立「昆仑—西王母」公共文化联想，不展开宗教修持。',
    source: SRC,
    todayLink: '博物馆与戏曲中的西王母，多是文学与民俗形象。',
    tellable: '西王母是昆仑故事里最亮的名字之一。',
    restore: quiz(
      '西王母在公共文化记忆中，常与哪一山系想象相连？',
      [
        { id: 'a', text: '昆仑等仙山叙事', correct: true },
        { id: 'b', text: '现代写字楼电梯', correct: false },
        { id: 'c', text: '南极科考站专名', correct: false },
      ],
      '昆仑联想。',
    ),
  },
  {
    id: 'A-R06-N-010',
    name: '精卫印象',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L02'],
    oneLiner: '小鸟衔石填海，是意志的寓言。',
    coreLore:
      '精卫填海是广为人知的神话叙事，常被解读为不屈与执着。神话的教育功能，往往在「讲志气」而不在「教人真去填海」。',
    source: SRC,
    todayLink: '遇到长期困难时，精卫是文化里的精神表情包。',
    tellable: '精卫的翅膀很小，志向却很大。',
    restore: quiz(
      '精卫故事更常被用来象征？',
      [
        { id: 'a', text: '执着与不屈', correct: true },
        { id: 'b', text: '放弃一切努力', correct: false },
        { id: 'c', text: '禁止靠近海洋', correct: false },
      ],
      '寓言意义。',
    ),
  },
  {
    id: 'A-R06-N-011',
    name: '夸父印象',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L02'],
    oneLiner: '追日的脚步，量出古典的豪迈。',
    coreLore:
      '夸父逐日是著名神话，常被读作对极限的挑战与悲壮。与精卫对照，可见《山海经》系统里「小物大力」与「巨人大志」两种想象。',
    source: SRC,
    todayLink: '运动会上的「追光」，有时会让人想起这个名字。',
    tellable: '夸父把太阳，当成可以追的终点线。',
    restore: quiz(
      '夸父逐日故事的基调更接近？',
      [
        { id: 'a', text: '豪迈、挑战极限的神话叙事', correct: true },
        { id: 'b', text: '教人不要晒太阳的说明书', correct: false },
        { id: 'c', text: '现代导航故障报告', correct: false },
      ],
      '神话豪迈。',
    ),
  },
  {
    id: 'A-R06-N-012',
    name: '名物与图像',
    rarity: 'N',
    types: ['concept'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L04'],
    oneLiner: '经文只有字，后人给它画了上千年。',
    coreLore:
      '《山海经》本文多无原图（或图失传），后世插图系统发达。图像是再创作，帮助记忆，也可能固定某种想象——阅读时要有「图是解释」的意识。',
    source: SRC,
    todayLink: '打开任何山海经绘本，先看作者怎么画。',
    tellable: '异兽的脸，有一半是画家给的。',
    restore: quiz(
      '关于《山海经》图像，更稳妥的是？',
      [
        { id: 'a', text: '后世插图多是再创作，助记也带解释', correct: true },
        { id: 'b', text: '所有图都是拍照实录', correct: false },
        { id: 'c', text: '禁止任何配图', correct: false },
      ],
      '图是再创作。',
    ),
  },
  {
    id: 'A-R06-N-013',
    name: '勿迷信操作',
    rarity: 'N',
    types: ['ethics', 'concept'],
    authTag: 'public_edu',
    region: 'R06',
    learnIds: ['R06-X-ethics'],
    oneLiner: '神话可读、可画，不教迷信法术。',
    coreLore:
      '仙山展区止于文化与艺术理解。不提供任何「召唤/修炼」操作指南，不鼓励封建迷信活动。把神怪留在故事与展览里。',
    source: '公共文化教育原则。',
    todayLink: '欣赏奇幻，过好现实。',
    tellable: '我收集的是故事，不是咒语。',
    restore: quiz(
      '在本展览中对待神怪内容，应？',
      [
        { id: 'a', text: '作为文化艺术理解', correct: true },
        { id: 'b', text: '按游戏教的去搞迷信', correct: false },
        { id: 'c', text: '完全禁止阅读神话', correct: false },
      ],
      '文化 ≠ 迷信实践。',
    ),
  },
  {
    id: 'A-R06-N-014',
    name: '与五区对照',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R06',
    learnIds: ['R06-L04'],
    oneLiner: '史证器物与经载想象，是两条腿走路。',
    coreLore:
      '中原楚蜀江南塞北提供史证/民俗质感；仙山提供神话燃料。合在一起，才接近中国人「既脚踏实地，又仰望奇文」的文化习惯。',
    source: '本游戏课程设计。',
    todayLink: '你可以早上逛青铜馆，晚上读一则神话。',
    tellable: '一只脚在鼎边，一只脚在昆仑。',
    restore: quiz(
      '史证展区与仙山展区的关系更接近？',
      [
        { id: 'a', text: '互补：物证与想象并置', correct: true },
        { id: 'b', text: '互相取消', correct: false },
        { id: 'c', text: '完全重复', correct: false },
      ],
      '互补。',
    ),
  },
  {
    id: 'A-R06-N-015',
    name: '海外传播中的山海',
    rarity: 'N',
    types: ['concept', 'classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L05'],
    oneLiner: '异兽图像正成为跨文化的「中国奇想」名片。',
    coreLore:
      '近现代以来，《山海经》图像与故事通过翻译、展览与流行文化走向世界。传播中会变形，这是正常的；关键是标明来源与再创作。',
    source: SRC,
    todayLink: '可与「海丝」展区对照：物走海路，故事走译路。',
    tellable: '异兽漂洋过海，靠的是船，也靠译本。',
    restore: quiz(
      '山海经故事走向世界时，应？',
      [
        { id: 'a', text: '允许再创作并尽量标明来源', correct: true },
        { id: 'b', text: '禁止任何翻译', correct: false },
        { id: 'c', text: '假装是他国原创且无来源', correct: false },
      ],
      '传播与署名。',
    ),
  },
  {
    id: 'A-R06-R-016',
    name: '烛龙印象',
    rarity: 'R',
    types: ['classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L02'],
    oneLiner: '开目为昼、闭目为夜的夸张宇宙龙。',
    coreLore:
      '烛龙等记载以极度夸张解释昼夜，是神话思维的典型：用人格/神格过程说明自然现象。欣赏其诗性，而不是当作天体物理学。',
    source: SRC,
    todayLink: '科学课讲地球自转，文学课可以讲烛龙。',
    tellable: '烛龙一眨眼，古典的昼夜就有了戏剧。',
    restore: quiz(
      '烛龙神话更适合被理解为？',
      [
        { id: 'a', text: '解释自然的诗性神话', correct: true },
        { id: 'b', text: '现代卫星工程图纸', correct: false },
        { id: 'c', text: '天气预报 App 源码', correct: false },
      ],
      '诗性解释。',
    ),
  },
  {
    id: 'A-R06-N-017',
    name: '读经三法',
    rarity: 'N',
    types: ['concept'],
    authTag: 'public_edu',
    region: 'R06',
    learnIds: ['R06-L03'],
    oneLiner: '好奇、对照、不武断。',
    coreLore:
      '读《山海经》可：①保持好奇；②与地理、民俗、艺术对照；③区分记载、注疏与现代戏说。三法能减少被谣言带着跑。',
    source: '阅读方法公教。',
    todayLink: '刷短视频遇到山海经，先找原典句子。',
    tellable: '读经不是背怪，是练习提问。',
    restore: quiz(
      '读《山海经》较推荐的态度是？',
      [
        { id: 'a', text: '好奇、对照、不武断', correct: true },
        { id: 'b', text: '全盘当新闻事实', correct: false },
        { id: 'c', text: '拒绝一切阅读', correct: false },
      ],
      '三法。',
    ),
  },
  {
    id: 'A-R06-N-018',
    name: '山经与海经',
    rarity: 'N',
    types: ['classic', 'concept'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L03'],
    oneLiner: '书名里就有山与海的两扇门。',
    coreLore:
      '《山海经》传统上可粗分为山经、海经等部分（具体结构随版本与研究而论）。入门记住：它既写山中之物，也写海外之闻，空间感极大。',
    source: SRC,
    todayLink: '打开目录，先建立「山/海」两块地图。',
    tellable: '山海经的封面，就是一张折叠的世界。',
    restore: quiz(
      '书名「山海经」提示文本空间感？',
      [
        { id: 'a', text: '既有山系也有海外想象', correct: true },
        { id: 'b', text: '只写厨房菜单', correct: false },
        { id: 'c', text: '只写城市地铁', correct: false },
      ],
      '山与海。',
    ),
  },
  {
    id: 'A-R06-N-019',
    name: '再创作伦理',
    rarity: 'N',
    types: ['ethics', 'concept'],
    authTag: 'public_edu',
    region: 'R06',
    learnIds: ['R06-X-ethics'],
    oneLiner: '可以改写，请标明你在改写。',
    coreLore:
      '国风二创繁荣，但应避免把戏说说成考古定论，避免侮辱性改编与虚假「出土新闻」。本游戏每张经载卡都尽量标明性质，供对照。',
    source: '内容伦理倡导。',
    todayLink: '创作自由与信息诚实可以并存。',
    tellable: '戏说有趣，诚实更久。',
    restore: quiz(
      '对神话再创作，更合适的是？',
      [
        { id: 'a', text: '允许创作并标明戏说/再创作', correct: true },
        { id: 'b', text: '伪造考古新闻欺骗公众', correct: false },
        { id: 'c', text: '禁止一切艺术创作', correct: false },
      ],
      '标明再创作。',
    ),
  },
  {
    id: 'A-R06-SR-020',
    name: '仙山小谱',
    rarity: 'SR',
    types: ['concept', 'classic'],
    authTag: 'classic_shanhai',
    region: 'R06',
    learnIds: ['R06-L01', 'R06-L02', 'R06-L04'],
    oneLiner: '昆仑、异兽、经册——带走想象的海拔。',
    coreLore:
      '仙山展区希望你带走：昆仑等坐标；九尾、精卫、夸父等公共神话；经载与史证的标签意识；以及把神话当文化资源而非迷信操作的态度。',
    source: '本区域课程纲要汇总。',
    todayLink: '合上山海册，仍可把好奇留在生活里。',
    tellable: '仙山这一路，我记住了山、兽、册和标签。',
    restore: quiz(
      '仙山展区最核心的学习主题更接近？',
      [
        { id: 'a', text: '山海经想象·异兽·经载标签', correct: true },
        { id: 'b', text: '只学瓷器釉料配方', correct: false },
        { id: 'c', text: '现代航空管制条例全文', correct: false },
      ],
      '经载想象是主轴。',
    ),
  },
];
