import type { LoreCard, QuizOption } from '../core/types';
import {
  BOARD,
  kitCompass,
  kitExportPorcelain,
  kitSeaShip,
  kitSpicePouch,
  kitBoat,
} from './shapeKits.ts';

/** 海丝 R08 · 20 张 · 海洋航路、外销、互鉴与翻译 */

function shape(pieces: ReturnType<typeof kitSeaShip>): LoreCard['restore'] {
  return { kind: 'shape', board: { ...BOARD }, pieces };
}
function quiz(prompt: string, options: QuizOption[], explain: string): LoreCard['restore'] {
  return { kind: 'quiz', prompt, options, explain };
}

const SRC =
  '海上丝绸之路与中外交流通识；公开博物馆与海洋史公教。本展示为再创作示意，非正式馆藏复制。';

export const HAISI_ARTIFACTS: LoreCard[] = [
  {
    id: 'A-R08-SR-001',
    name: '海船意象',
    rarity: 'SR',
    types: ['folk'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L01'],
    oneLiner: '帆与船体，把陆地的故事送进季风。',
    coreLore:
      '海船是海上交通的核心载具。不同时代船型差异很大，本卡只建立「帆船航海」的公共印象：人、货、知识可以借风跨越海岸。',
    source: SRC,
    todayLink: '港口城市的天际线，仍从船开始生长。',
    tellable: '海丝的第一笔，写在帆布上。',
    restore: shape(kitSeaShip()),
  },
  {
    id: 'A-R08-R-002',
    name: '罗盘印象',
    rarity: 'R',
    types: ['craft'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L02'],
    oneLiner: '指针找到北，航线才敢写长。',
    coreLore:
      '指南针是中国重大发明，对航海定向意义深远。它象征「把方向变成可携带的知识」。具体航海罗盘形制随时代变化。',
    source: SRC,
    todayLink: '手机地图的方向标，是这条故事的数码后代。',
    tellable: '罗盘让大海少一点迷路。',
    restore: shape(kitCompass()),
  },
  {
    id: 'A-R08-R-003',
    name: '外销瓷盘',
    rarity: 'R',
    types: ['ceramic'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L03'],
    oneLiner: '为远方餐桌绘制的蓝白与开光。',
    coreLore:
      '历史上大量中国瓷器经海路外销，纹样常兼顾本地与海外市场口味。外销瓷是「中国制造」很早的全球名片，也记录审美对话。',
    source: SRC,
    todayLink: '博物馆里的克拉克瓷等名称，指向这段贸易史。',
    tellable: '有的盘子，比旅人先到达对岸。',
    restore: shape(kitExportPorcelain()),
  },
  {
    id: 'A-R08-R-004',
    name: '香料囊',
    rarity: 'R',
    types: ['folk', 'craft'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L04'],
    oneLiner: '气味也是货物，也是记忆。',
    coreLore:
      '香料是海路贸易的重要商品门类，连接东南亚、南亚与更广阔市场。香料改变饮食与医药，也改变港口城市的气味景观。',
    source: SRC,
    todayLink: '厨房香料架上，可能藏着一条看不见的古航线。',
    tellable: '海丝有时不用看，用闻。',
    restore: shape(kitSpicePouch()),
  },
  {
    id: 'A-R08-N-005',
    name: '海丝知一张',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L05'],
    oneLiner: '海上丝绸之路：海洋上的交往网络。',
    coreLore:
      '「海上丝绸之路」是概括中外通过海洋进行贸易与文化交流的历史网络。它不是单一航线，而是多港口、多季风季节、多商品的体系。',
    source: SRC,
    todayLink: '今天的远洋航运与港口合作，仍在写海洋章节。',
    tellable: '海丝是一张被潮水浸湿的联络网。',
    restore: quiz(
      '更准确理解海丝的是？',
      [
        { id: 'a', text: '多港口、多季节的海洋交往网络', correct: true },
        { id: 'b', text: '只有一条永不改道的独木桥', correct: false },
        { id: 'c', text: '与海洋无关的陆上牧场', correct: false },
      ],
      '网络。',
    ),
  },
  {
    id: 'A-R08-N-006',
    name: '季风航海',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L01'],
    oneLiner: '风有季节，船有班期。',
    coreLore:
      '印度洋与西太平洋航海高度依赖季风。商船往往顺风来、顺风去，港口因此形成节奏。理解季风，是理解古代海员时间表的钥匙。',
    source: SRC,
    todayLink: '气象对物流的影响，古今皆然。',
    tellable: '古人看风色，决定何时出海。',
    restore: quiz(
      '季风对古代航海的意义是？',
      [
        { id: 'a', text: '影响航期与往返节奏', correct: true },
        { id: 'b', text: '完全无影响', correct: false },
        { id: 'c', text: '只影响登山', correct: false },
      ],
      '风即班期。',
    ),
  },
  {
    id: 'A-R08-N-007',
    name: '港口城市',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L05'],
    oneLiner: '港不只是码头，是翻译与混成的剧场。',
    coreLore:
      '泉州、广州等港口在不同历史时期成为中外商人、水手、宗教与语言交汇之地。港口文明的特征是混成：饮食、信仰建筑与方言都可能留下痕迹。',
    source: SRC,
    todayLink: '走老城街巷，有时比只看货柜更懂港口。',
    tellable: '港口教人：不同口音可以做邻居。',
    restore: quiz(
      '历史港口城市常见的文化特征是？',
      [
        { id: 'a', text: '多元人群与文化混成', correct: true },
        { id: 'b', text: '绝对单一、从不往来', correct: false },
        { id: 'c', text: '禁止任何贸易', correct: false },
      ],
      '混成。',
    ),
  },
  {
    id: 'A-R08-N-008',
    name: '郑和印象',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L01'],
    oneLiner: '大规模远航的公共历史记忆坐标。',
    coreLore:
      '郑和船队是中国海洋史上广为人知的远航事件，常被用于讨论朝贡、贸易与航海能力。本卡建立公共记忆入口，细节以史学研究为准。',
    source: SRC,
    todayLink: '相关博物馆与遗址公园提供更系统的展陈。',
    tellable: '郑和的名字，像一枚盖在海图上的印章。',
    restore: quiz(
      '郑和在公共文化记忆中，主要与什么相连？',
      [
        { id: 'a', text: '明代大规模远洋航行', correct: true },
        { id: 'b', text: '发明蒸汽火车', correct: false },
        { id: 'c', text: '只与登山有关', correct: false },
      ],
      '远航记忆。',
    ),
  },
  {
    id: 'A-R08-N-009',
    name: '翻译与通事',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L06'],
    oneLiner: '没有翻译，货物到了，意思还在海上。',
    coreLore:
      '跨语际贸易依赖通事、译员与混成语言。翻译是海丝的「软件基础设施」。理解交流，不能只数船舱吨位。',
    source: SRC,
    todayLink: '今天的同传与本地化行业，仍是港口的灵魂工种。',
    tellable: '海丝有人运瓷，也有人运句子。',
    restore: quiz(
      '跨海贸易中翻译的作用是？',
      [
        { id: 'a', text: '沟通语言与信息', correct: true },
        { id: 'b', text: '让交流停止', correct: false },
        { id: 'c', text: '与贸易无关', correct: false },
      ],
      '语言基础设施。',
    ),
  },
  {
    id: 'A-R08-N-010',
    name: '宗教建筑余韵',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L05'],
    oneLiner: '港口的天际线，有时包含外来的屋顶轮廓。',
    coreLore:
      '历史上港口城市可能出现多种宗教与礼俗建筑遗存，反映侨民与商旅社群生活。欣赏建筑多样性，以尊重与文保为前提。',
    source: SRC,
    todayLink: '文明互鉴可以在砖瓦的弧度里看见。',
    tellable: '有的信仰，随船靠岸，把屋顶留下。',
    restore: quiz(
      '港口多元宗教建筑遗存，主要说明？',
      [
        { id: 'a', text: '历史上的人群往来与社群生活', correct: true },
        { id: 'b', text: '证明只允许一种建筑风格', correct: false },
        { id: 'c', text: '与海洋史无关', correct: false },
      ],
      '往来的物证。',
    ),
  },
  {
    id: 'A-R08-N-011',
    name: '沉船考古',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L03'],
    oneLiner: '海底的货舱，是忽然停住的航程。',
    coreLore:
      '水下考古发现的沉船与外销瓷等，为海路贸易提供关键证据。沉船不是宝藏猎奇秀，而是需要科学发掘与文保伦理的现场。',
    source: SRC,
    todayLink: '支持合法考古，抵制盗捞。',
    tellable: '沉船把失败的航次，变成后来的课堂。',
    restore: quiz(
      '对待沉船文物，更合适的是？',
      [
        { id: 'a', text: '科学考古与保护', correct: true },
        { id: 'b', text: '私自盗捞倒卖', correct: false },
        { id: 'c', text: '炸毁遗址取乐', correct: false },
      ],
      '文保伦理。',
    ),
  },
  {
    id: 'A-R08-N-012',
    name: '茶瓷丝三角',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L03', 'R08-L04'],
    oneLiner: '中国出海的常见「三件套」印象。',
    coreLore:
      '茶、瓷、丝常被并提为历史上中国对外输出的重要商品门类（不同时期比重不同）。它们把日常生活美学送上全球餐桌与衣橱。',
    source: SRC,
    todayLink: '下午茶里的瓷杯与茶叶，可能隔着很远的祖先航线。',
    tellable: '茶瓷丝，是三条能漂洋的中国气味与触感。',
    restore: quiz(
      '茶、瓷、丝在海贸叙事中常被视为？',
      [
        { id: 'a', text: '重要的中国外销商品门类', correct: true },
        { id: 'b', text: '与贸易无关的禁运口令', correct: false },
        { id: 'c', text: '只有现代才出现的发明', correct: false },
      ],
      '外销名片。',
    ),
  },
  {
    id: 'A-R08-N-013',
    name: '陆丝与海丝',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L05'],
    oneLiner: '沙漠驼铃与海上帆影，是姊妹篇。',
    coreLore:
      '陆上丝路与海上丝路都是后起概括，强调跨区域交往。二者路线、商品、风险不同，却共同书写「中国与世界互相看见」的长故事。可与塞北展区对照。',
    source: SRC,
    todayLink: '一张完整的交流史，需要沙漠与海洋两章。',
    tellable: '驼铃和船铃，响的是同一种远方。',
    restore: quiz(
      '陆丝与海丝的关系更接近？',
      [
        { id: 'a', text: '不同路径的跨区域交往', correct: true },
        { id: 'b', text: '完全相同的一条路', correct: false },
        { id: 'c', text: '互相否认对方存在', correct: false },
      ],
      '姊妹路径。',
    ),
  },
  {
    id: 'A-R08-N-014',
    name: '侨批与家书印象',
    rarity: 'N',
    types: ['folk', 'concept'],
    authTag: 'folk',
    region: 'R08',
    learnIds: ['R08-L06'],
    oneLiner: '钱与字一起漂洋，连着两头的家。',
    coreLore:
      '侨批等历史现象显示海外移民与家乡的汇款、书信网络。海洋不只运货，也运牵挂。具体制度因地因时而异。',
    source: '华侨史与民俗通识。',
    todayLink: '一通越洋视频，是数字时代的家书。',
    tellable: '有的航线，装的是思念的重量。',
    restore: quiz(
      '侨批现象主要说明？',
      [
        { id: 'a', text: '海外与家乡的汇款书信联系', correct: true },
        { id: 'b', text: '禁止一切通信', correct: false },
        { id: 'c', text: '与海洋移民无关', correct: false },
      ],
      '家书网络。',
    ),
  },
  {
    id: 'A-R08-N-015',
    name: '互鉴不是单向',
    rarity: 'N',
    types: ['concept', 'ethics'],
    authTag: 'public_edu',
    region: 'R08',
    learnIds: ['R08-X-ethics'],
    oneLiner: '船来船往，影响往往是双向的。',
    coreLore:
      '文化交流常被简化为「输出」或「输入」。更公允的图景是互鉴：作物、技艺、艺术母题与词汇在多向流动。避免文明傲慢与虚无。',
    source: '文明互鉴公共表述。',
    todayLink: '餐桌上的番茄与辣椒，也是全球流动的结果。',
    tellable: '海风吹向两边，文化也是。',
    restore: quiz(
      '理解中外交流，更合适的是？',
      [
        { id: 'a', text: '看见双向互鉴与多向流动', correct: true },
        { id: 'b', text: '只承认单向且永恒的高下', correct: false },
        { id: 'c', text: '否认任何接触', correct: false },
      ],
      '互鉴。',
    ),
  },
  {
    id: 'A-R08-R-016',
    name: '沿海舟楫',
    rarity: 'R',
    types: ['folk'],
    authTag: 'folk',
    region: 'R08',
    learnIds: ['R08-L01'],
    oneLiner: '近海的船，连着渔汛与短途贸易。',
    coreLore:
      '除远洋商船外，近海渔舟与短途货船构成海洋生活的基底。海丝叙事若只谈宝船，会漏掉日常的咸味。',
    source: SRC,
    todayLink: '渔港的早市，是海洋史的活页。',
    tellable: '大海不只装史诗，也装早饭的鱼。',
    restore: shape(kitBoat()),
  },
  {
    id: 'A-R08-N-017',
    name: '语词借来借去',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L06'],
    oneLiner: '港口方言里，藏着外来的音节。',
    coreLore:
      '贸易带来借词与地名遗存。语言是柔软的货舱。本卡建立「听音辨交流」的兴趣，不展开专业词源学。',
    source: SRC,
    todayLink: '查一个外来词词源，像打开微型海丝。',
    tellable: '有的字，脚印盐分很重。',
    restore: quiz(
      '港口地区出现外来词，可能说明？',
      [
        { id: 'a', text: '历史上的接触与借用', correct: true },
        { id: 'b', text: '语言从未变化', correct: false },
        { id: 'c', text: '禁止任何交流', correct: false },
      ],
      '语言有航迹。',
    ),
  },
  {
    id: 'A-R08-N-018',
    name: '风险与勇气',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L01'],
    oneLiner: '风暴、礁石与疾病，是航程的隐形税。',
    coreLore:
      '古代航海风险极高。歌颂交流时，也应看见水手与商人的代价。历史不是只有成功靠岸的叙事。',
    source: SRC,
    todayLink: '尊重职业水手与海事安全规则。',
    tellable: '每一封平安家书，都可能穿过风暴。',
    restore: quiz(
      '谈论古代航海，较完整的是？',
      [
        { id: 'a', text: '既见交流成就，也见风险代价', correct: true },
        { id: 'b', text: '假装海洋从无风险', correct: false },
        { id: 'c', text: '只嘲笑失败者', correct: false },
      ],
      '成就与代价。',
    ),
  },
  {
    id: 'A-R08-N-019',
    name: '七区合图',
    rarity: 'N',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L05'],
    oneLiner: '从鼎到帆，中国故事需要整张地图。',
    coreLore:
      '中原楚蜀江南塞北仙山岁时海丝：本游戏的展区拼图到此更完整。海丝把「内部多样性」接上「外部交往」，使学习不封闭于国境线内的想象。',
    source: '本游戏课程总图。',
    todayLink: '你可以按展区列一份旅行与阅读清单。',
    tellable: '我从鼎走到帆，才觉得地图够用了。',
    restore: quiz(
      '海丝展区在整体课程中的作用是？',
      [
        { id: 'a', text: '连接内部多样性与外部交往', correct: true },
        { id: 'b', text: '取消所有其他展区', correct: false },
        { id: 'c', text: '只学陆地忽视海洋', correct: false },
      ],
      '合图。',
    ),
  },
  {
    id: 'A-R08-SR-020',
    name: '海丝小谱',
    rarity: 'SR',
    types: ['concept'],
    authTag: 'historic_inspired',
    region: 'R08',
    learnIds: ['R08-L01', 'R08-L03', 'R08-L06'],
    oneLiner: '船、针、瓷、香——带走海洋四印象。',
    coreLore:
      '海丝展区希望你带走：帆船与季风；罗盘定向；茶瓷丝与香料；港口混成与翻译；以及互鉴、文保与风险意识。海洋是中国故事不可删的一章。',
    source: '本区域课程纲要汇总。',
    todayLink: '下次吃香料菜、用瓷杯，想一想风从哪吹来。',
    tellable: '海丝这一路，我记住了帆、针、瓷和香。',
    restore: quiz(
      '海丝展区最核心的学习主题更接近？',
      [
        { id: 'a', text: '航海·港口·外销与互鉴', correct: true },
        { id: 'b', text: '只学纵目面具铸造温度', correct: false },
        { id: 'c', text: '现代浏览器内核源码', correct: false },
      ],
      '航海互鉴是主轴。',
    ),
  },
];
