import type { LoreCard, QuizOption } from '../core/types';
import {
  BOARD,
  kitCouplet,
  kitLantern,
  kitMooncake,
  kitZongzi,
  kitDrum,
  kitBoat,
} from './shapeKits.ts';

/** 岁时 R07 · 节日专题卡（约 16 张） */

function shape(pieces: ReturnType<typeof kitLantern>): LoreCard['restore'] {
  return { kind: 'shape', board: { ...BOARD }, pieces };
}
function quiz(prompt: string, options: QuizOption[], explain: string): LoreCard['restore'] {
  return { kind: 'quiz', prompt, options, explain };
}

const SRC = '中国传统节日与民俗通识；各地习俗有差异，以当地传统与公共文化说明为准。';

export const SEASONAL_ARTIFACTS: LoreCard[] = [
  {
    id: 'A-R07-SR-001',
    name: '春联',
    rarity: 'SR',
    types: ['seasonal', 'folk'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L01'],
    festivalIds: ['spring'],
    oneLiner: '红纸黑字贴上门，把祝福钉在一年的起点。',
    coreLore:
      '春联是春节常见民俗：用对仗工整的文句写在红纸上，贴于门侧。它把文学的对仗带进日常生活，也把家宅变成节日的舞台。',
    source: SRC,
    todayLink: '写不出长联，贴一句真诚的短句也很好。',
    tellable: '春联是门上的诗，等着一整年被推开。',
    restore: shape(kitCouplet()),
  },
  {
    id: 'A-R07-N-002',
    name: '春节知一张',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L01'],
    festivalIds: ['spring'],
    oneLiner: '岁始团圆、扫尘纳福的公共节奏。',
    coreLore:
      '春节是中国最重要的传统节日之一，核心主题常包括辞旧迎新、家庭团聚与祈福。具体食俗与仪式因地而异，尊重差异比背「标准答案」更重要。',
    source: SRC,
    todayLink: '无论在哪里过年，一句「平安」永远不过时。',
    tellable: '春节是把散落的人，重新聚成家的形状。',
    restore: quiz(
      '春节更核心的公共主题接近？',
      [
        { id: 'a', text: '辞旧迎新与团圆祈福', correct: true },
        { id: 'b', text: '只允许独自加班', correct: false },
        { id: 'c', text: '取消一切家庭联系', correct: false },
      ],
      '团圆与更新。',
    ),
  },
  {
    id: 'A-R07-R-003',
    name: '花灯',
    rarity: 'R',
    types: ['seasonal', 'folk'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L02'],
    festivalIds: ['lantern'],
    oneLiner: '灯火把夜晚变成可游玩的白昼。',
    coreLore:
      '花灯是元宵等节日的重要符号，观灯、灯会是公共娱乐与审美。灯笼也出现在其他喜庆场合，是「把光拿在手里」的民俗设计。',
    source: SRC,
    todayLink: '现代灯会与灯光秀，仍在延续「夜游」传统。',
    tellable: '花灯一亮，冬天的夜晚就有了表情。',
    restore: shape(kitLantern()),
  },
  {
    id: 'A-R07-N-004',
    name: '元宵与灯谜',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L02'],
    festivalIds: ['lantern'],
    oneLiner: '汤圆的圆，灯谜的巧，都在正月里。',
    coreLore:
      '元宵节在正月十五，常有观灯、吃汤圆/元宵、猜灯谜等活动。灯谜把文字游戏带进节日，体现民俗的机智与欢乐。',
    source: SRC,
    todayLink: '家庭灯谜会，是低成本的文化游戏。',
    tellable: '元宵的圆，是把答案和团圆煮在一起。',
    restore: quiz(
      '元宵节常见活动包括？',
      [
        { id: 'a', text: '观灯、食圆、灯谜等', correct: true },
        { id: 'b', text: '只允许关灯静坐', correct: false },
        { id: 'c', text: '取消正月', correct: false },
      ],
      '灯与圆。',
    ),
  },
  {
    id: 'A-R07-R-005',
    name: '粽子',
    rarity: 'R',
    types: ['seasonal', 'folk'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L03'],
    festivalIds: ['duanwu'],
    oneLiner: '箬叶包米，是可以握在手里的端午。',
    coreLore:
      '粽子是端午节标志性食品之一，以叶裹米蒸煮，风味因地而异。食品民俗把季节、植物与记忆包在一起，是活态文化最可亲的一层。',
    source: SRC,
    todayLink: '南甜北咸，都是正当的家乡答案。',
    tellable: '解开粽叶，像拆开一封来自夏天的短信。',
    restore: shape(kitZongzi()),
  },
  {
    id: 'A-R07-R-006',
    name: '龙舟鼓点',
    rarity: 'R',
    types: ['seasonal', 'musical'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L03'],
    festivalIds: ['duanwu'],
    oneLiner: '鼓声一密，船就有了集体的心跳。',
    coreLore:
      '龙舟竞渡是端午重要民俗活动，鼓点指挥节奏与协作。它展示的是社区动员与身体文化，而不只是「比赛输赢」。',
    source: SRC,
    todayLink: '看龙舟，也看岸上人的加油方式。',
    tellable: '龙舟的鼓，把许多人划成同一种呼吸。',
    restore: shape(kitDrum()),
  },
  {
    id: 'A-R07-N-007',
    name: '端午与纪念',
    rarity: 'N',
    types: ['seasonal', 'classic'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L03'],
    festivalIds: ['duanwu'],
    oneLiner: '有的地方把屈原的文学记忆编进节日。',
    coreLore:
      '端午节俗多元，部分地区与纪念屈原的叙事相连，也有其他地方性起源解释。尊重多元说法，把重点放在避疫、卫生、家庭与社区活动等公共层面。',
    source: SRC,
    todayLink: '读一句楚辞，再吃一枚粽，是很好的组合。',
    tellable: '端午的江上，有鼓，也有诗。',
    restore: quiz(
      '对待端午起源叙事，更合适的是？',
      [
        { id: 'a', text: '了解多元说法，尊重地方习俗', correct: true },
        { id: 'b', text: '只承认一种并贬低其他', correct: false },
        { id: 'c', text: '否认任何节日意义', correct: false },
      ],
      '多元民俗。',
    ),
  },
  {
    id: 'A-R07-R-008',
    name: '月饼',
    rarity: 'R',
    types: ['seasonal', 'folk'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L04'],
    festivalIds: ['midautumn'],
    oneLiner: '圆饼像月，切开又像分享的圆。',
    coreLore:
      '月饼是中秋常见节令食品，圆形象征团圆。花式与馅料极多，本身就是一部「口味地图」。节日食品让抽象的团圆变得可品尝。',
    source: SRC,
    todayLink: '小份分享比囤积更接近节日本意。',
    tellable: '月饼是可以吃的月亮副本。',
    restore: shape(kitMooncake()),
  },
  {
    id: 'A-R07-N-009',
    name: '中秋赏月',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L04'],
    festivalIds: ['midautumn'],
    oneLiner: '抬头看同一轮月，是跨越距离的古老通讯。',
    coreLore:
      '中秋在农历八月十五，赏月、思乡、团圆是常见主题。月亮成为中国诗词与视觉艺术的核心意象之一，使节日具有强烈的审美属性。',
    source: SRC,
    todayLink: '即使独处，也可以把月光当成一封短信。',
    tellable: '中秋的月亮，是写给所有人的抄送。',
    restore: quiz(
      '中秋更核心的文化主题接近？',
      [
        { id: 'a', text: '赏月与团圆思念', correct: true },
        { id: 'b', text: '禁止看天', correct: false },
        { id: 'c', text: '只与购物有关', correct: false },
      ],
      '月与人。',
    ),
  },
  {
    id: 'A-R07-N-010',
    name: '清明踏青',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L05'],
    festivalIds: ['qingming'],
    oneLiner: '既慎终追远，也走向春天的田野。',
    coreLore:
      '清明既有祭扫先人的礼仪层面，也有踏青的时令活动。现代公共倡导文明祭扫与生态保护，使节日在情感与公德之间取得平衡。',
    source: SRC,
    todayLink: '用一束花、一次沉默，也可以完成郑重。',
    tellable: '清明的风，有记忆，也有新绿。',
    restore: quiz(
      '清明较完整的理解包括？',
      [
        { id: 'a', text: '纪念先人与踏青时令（并文明环保）', correct: true },
        { id: 'b', text: '只允许燃放危险物品', correct: false },
        { id: 'c', text: '与春天完全无关', correct: false },
      ],
      '纪念 + 时令。',
    ),
  },
  {
    id: 'A-R07-N-011',
    name: '七夕诗笺',
    rarity: 'N',
    types: ['seasonal', 'classic'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L05'],
    festivalIds: ['qixi'],
    oneLiner: '星桥与诗句，谈的是等待与重逢。',
    coreLore:
      '七夕与牛郎织女传说相关，是传统中与爱情、乞巧相关的节日节点。文学与民俗交织，使星空成为可读的故事书。本卡作文化理解，不涉迷信操作。',
    source: SRC,
    todayLink: '现代表达爱意的方式很多，尊重与承诺仍是核心。',
    tellable: '七夕把银河，变成可以盼望的距离。',
    restore: quiz(
      '七夕文化记忆主要关联？',
      [
        { id: 'a', text: '星象传说与情感主题', correct: true },
        { id: 'b', text: '仅与滑雪有关', correct: false },
        { id: 'c', text: '禁止任何诗歌', correct: false },
      ],
      '传说与情感。',
    ),
  },
  {
    id: 'A-R07-N-012',
    name: '重阳登高',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L05'],
    festivalIds: ['chongyang'],
    oneLiner: '九月登高，把视野与敬老放在同一条路上。',
    coreLore:
      '重阳在九月初九，传统有登高、赏菊等活动，当代也强调敬老。数字成双的「九」与登高，构成时令与伦理的双重主题。',
    source: SRC,
    todayLink: '给长辈打一个电话，也是一种登高。',
    tellable: '重阳的高度，量的是心，不只是山。',
    restore: quiz(
      '重阳的当代公共主题常包括？',
      [
        { id: 'a', text: '登高时令与敬老', correct: true },
        { id: 'b', text: '鼓励歧视老人', correct: false },
        { id: 'c', text: '取消秋天', correct: false },
      ],
      '登高与敬老。',
    ),
  },
  {
    id: 'A-R07-N-013',
    name: '冬至一阳',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L05'],
    festivalIds: ['dongzhi'],
    oneLiner: '白昼最短之后，光会一点点回来。',
    coreLore:
      '冬至是重要节气与节日，标志日照变化的转折。民间有吃饺子/汤圆等不同食俗。「一阳来复」的古典表述，把天文感受写成希望。',
    source: SRC,
    todayLink: '冬至宜温热饮食，也宜早睡。',
    tellable: '冬至是光的转折点，也是餐桌上的家的形状。',
    restore: quiz(
      '冬至在时令上的意义接近？',
      [
        { id: 'a', text: '日照转折的重要节气/节日', correct: true },
        { id: 'b', text: '全年白昼最长的唯一解释', correct: false },
        { id: 'c', text: '与太阳运行无关', correct: false },
      ],
      '光的拐点。',
    ),
  },
  {
    id: 'A-R07-R-014',
    name: '岁舟（泛节日）',
    rarity: 'R',
    types: ['seasonal', 'folk'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L06'],
    festivalIds: ['duanwu', 'spring'],
    oneLiner: '船在节日里，不只是交通，也是仪式道具。',
    coreLore:
      '从龙舟到渡船意象，水上载具常进入节日表演。它提醒我们：交通工具可以在节庆中被重新命名为「共同行动的身体」。',
    source: SRC,
    todayLink: '看任何巡游，注意节奏如何统一人群。',
    tellable: '节日的船，装的是同一种鼓点。',
    restore: shape(kitBoat()),
  },
  {
    id: 'A-R07-N-015',
    name: '二十四节气名片',
    rarity: 'N',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L06'],
    festivalIds: ['solar'],
    oneLiner: '把一年切成可感知的物候段落。',
    coreLore:
      '二十四节气是中国人观察太阳周年运动形成的时间知识体系，已列入人类非物质文化遗产代表作名录。它服务农事与生活节奏，也是美学与饮食的灵感表。',
    source: '节气非遗与通识公教。',
    todayLink: '关注「今日节气」，是一种缓慢的现代养生法。',
    tellable: '节气是大自然写给日历的脚注。',
    restore: quiz(
      '二十四节气主要依据？',
      [
        { id: 'a', text: '太阳周年运动与物候总结', correct: true },
        { id: 'b', text: '随机抽签', correct: false },
        { id: 'c', text: '仅由电商大促决定', correct: false },
      ],
      '天文学 + 生活。',
    ),
  },
  {
    id: 'A-R07-SR-016',
    name: '岁时小谱',
    rarity: 'SR',
    types: ['seasonal', 'concept'],
    authTag: 'seasonal',
    region: 'R07',
    learnIds: ['R07-L01', 'R07-L03', 'R07-L04', 'R07-L06'],
    festivalIds: ['spring', 'duanwu', 'midautumn', 'solar'],
    oneLiner: '春联、花灯、粽与月——把一年过成故事。',
    coreLore:
      '岁时专题希望你带走：春节的更新与团圆；元宵的灯与圆；端午的叶与鼓；中秋的月与饼；以及节气作为更细的时间刻度。节日是活的课程，在家里就能上。',
    source: '本专题课程纲要汇总。',
    todayLink: '选一个即将到来的节日，认真过一次「有解释的节」。',
    tellable: '我过年，不只吃，也读懂了一点点为什么吃。',
    restore: quiz(
      '岁时专题的核心学习目标是？',
      [
        { id: 'a', text: '理解主要节日主题与物候节奏', correct: true },
        { id: 'b', text: '只学习刷单技巧', correct: false },
        { id: 'c', text: '取消所有传统节日', correct: false },
      ],
      '活的时间表。',
    ),
  },
];
