import type { BeastTemplate } from '../core/types.ts';

/**
 * 《山海问兽》图鉴模板。
 *
 * quote 一律取《山海经·南山经》原文（鹊山首脉）；plain 为白话直译；
 * shape/sound/nature 是「问兽」三轴线索，答案与原文严格对应。
 * 数值 tier：1 杂兽 2 灵兽 3 异兽 4 大妖 5 山主级。
 */

export const BEASTS: BeastTemplate[] = [
  {
    id: 'xingxing',
    name: '狌狌',
    pinyin: 'xīng xīng',
    quote: '有兽焉，其状如禺而白耳，伏行人走，其名曰狌狌，食之善走。',
    plain: '长得像猿猴，生着白耳朵，既能伏行也能像人一样直立行走，名叫狌狌。吃了它的肉，脚力会变好。',
    nature: '性灵而怯，见人先伏行观望，无恶意。',
    shape: '形如猿猴（禺），耳朵是白色的。',
    sound: '行进时几乎没有声音，伏行贴近。',
    effect: '食之善走',
    tier: 1,
    base: { hp: 40, atk: 8, def: 3, spd: 12 },
    exp: 14,
    mountains: ['zhaoyao'],
    kit: {
      passive: '白耳听风',
      passiveDesc: '佩戴后身法 +2（食之善走的余荫）。',
      active: { name: '伏行', desc: '下次攻击必定先手，并多两成力道。' },
    },
    drops: ['yupai'],
    art: { tint: '#9c6b4a', silhouette: 'ape', marks: 2 },
  },
  {
    id: 'baiyuan',
    name: '白猿',
    quote: '又东三百里，曰堂庭之山，多棪木，多白猿，多水玉，多黄金。',
    plain: '堂庭山上多棪木，多白猿，多水玉，多黄金。白猿是山中灵物，善攀援，臂长过膝。',
    nature: '性好戏闹，爱夺路人果食，会以臂长攀树远遁。',
    shape: '通体白毛，臂长过膝，形似猿。',
    sound: '长啸清越，山中回声不断。',
    effect: '棪木之实所养，力大身捷',
    tier: 1,
    base: { hp: 34, atk: 9, def: 2, spd: 14 },
    exp: 12,
    mountains: ['tangting', 'yuanyi'],
    kit: {
      passive: '臂长',
      passiveDesc: '佩戴后暴击一击的概率提高。',
      active: { name: '掷果', desc: '掷出棪木果实，造成小额伤害并回复少量气。' },
    },
    drops: ['yanmu_shi'],
    art: { tint: '#e8e2d4', silhouette: 'ape', marks: 0 },
  },
  {
    id: 'fuchong',
    name: '蝮虫',
    pinyin: 'fù chóng',
    quote: '又东三百八十里，曰猿翼之山，其中多怪兽，水多怪鱼，多白玉，多蝮虫，多怪蛇，多怪木，不可以上。',
    plain: '猿翼山中多怪兽，水中多怪鱼，多白玉、蝮虫、怪蛇、怪木。山势险恶，人不可攀上。',
    nature: '毒虫，性阴伏，常藏于石隙落叶之下。',
    shape: '蛇形而粗短，色如败叶。',
    sound: '无声，唯鳞擦石之沙沙。',
    effect: '毒也，非药——沾其涎者染瘴',
    tier: 1,
    base: { hp: 30, atk: 11, def: 2, spd: 10 },
    exp: 15,
    mountains: ['yuanyi'],
    kit: {
      passive: '毒涎',
      passiveDesc: '佩戴后战斗开始时使敌方染瘴。',
      active: { name: '啮', desc: '撕咬并注入瘴毒。' },
    },
    drops: ['feidian'],
    art: { tint: '#6b7a45', silhouette: 'serpent', marks: 0 },
  },
  {
    id: 'guaishe',
    name: '怪蛇',
    quote: '又东三百八十里，曰猿翼之山，其中多怪兽，水多怪鱼，多白玉，多蝮虫，多怪蛇，多怪木，不可以上。',
    plain: '猿翼山多怪蛇，与蝮虫共生。其形巨细无常，山民不敢直呼其名。',
    nature: '嗜热，择瘴深处盘踞，惧寒凉之气。',
    shape: '蛇身而纹路怪异，鳞片杂色。',
    sound: '吐信有声，嘶嘶如沸。',
    effect: '皮可制鼓，声沉',
    tier: 1,
    base: { hp: 45, atk: 12, def: 4, spd: 11 },
    exp: 18,
    mountains: ['yuanyi'],
    kit: {
      passive: '怪纹',
      passiveDesc: '佩戴后受到的瘴伤害减半。',
      active: { name: '缠绞', desc: '缠住对方，本回合其攻击减力。' },
    },
    drops: ['shedai'],
    art: { tint: '#4f5d3a', silhouette: 'serpent', marks: 3 },
  },
  {
    id: 'lushu',
    name: '鹿蜀',
    quote: '有兽焉，其状如马而白首，其文如虎而赤尾，其音如谣，其名曰鹿蜀，佩之宜子孙。',
    plain: '形状像马，白头，身上的斑纹如虎，尾是赤色，鸣声像人在唱歌，名叫鹿蜀。佩戴它的皮毛，多子多孙、家道兴旺。',
    nature: '祥瑞而警觉，闻人声即入林，无攻意。',
    shape: '形如马，白首虎纹赤尾。',
    sound: '其音如谣——像有人在远处唱歌。',
    effect: '佩之宜子孙',
    tier: 2,
    base: { hp: 55, atk: 10, def: 5, spd: 12 },
    exp: 22,
    mountains: ['niuyang'],
    kit: {
      passive: '宜子孙',
      passiveDesc: '佩戴后生命上限提高一成。',
      active: { name: '谣音', desc: '唱一段山谣，为我方回复生命。' },
    },
    drops: ['lushu_pi'],
    art: { tint: '#c88a4e', silhouette: 'horse', marks: 0 },
  },
  {
    id: 'xuangui',
    name: '旋龟',
    quote: '怪水出焉，而东流注于宪翼之水。其中多玄龟，其状如龟而鸟首虺尾，其名曰旋龟，其音如判木，佩之不聋，可以为底。',
    plain: '怪水中多黑色龟，龟身鸟头毒蛇尾，名叫旋龟。叫声像劈木头。佩用它就不聋，还可以治足茧。',
    nature: '沉默守水，性坚忍，被激怒时以身相撞。',
    shape: '龟身鸟首，尾如毒蛇。',
    sound: '其音如判木——像劈开木头的闷响。',
    effect: '佩之不聋，可以为底',
    tier: 2,
    base: { hp: 70, atk: 12, def: 8, spd: 6 },
    exp: 26,
    mountains: ['niuyang', 'dishan'],
    kit: {
      passive: '不聋',
      passiveDesc: '佩戴后防御 +3。',
      active: { name: '玄甲', desc: '龟甲映玄光，两回合内受伤大减。' },
    },
    drops: ['guijia'],
    art: { tint: '#3c4a52', silhouette: 'turtle', marks: 0 },
  },
  {
    id: 'lu',
    name: '鯥',
    pinyin: 'lù',
    quote: '又东三百里柢山，多水，无草木。有鱼焉，其状如牛，陵居，蛇尾有翼，其羽在魼下，其音如留牛，其名曰鯥，冬死而夏生，食之无肿疾。',
    plain: '柢山多水无草木。有一种鱼，形状像牛，住在山坡上，蛇尾带翼，羽毛长在胁下，叫声像犁牛，名叫鯥。冬天蛰伏如死，夏天复活。吃了它不得肿疾。',
    nature: '冬死夏生——蛰伏时气若游丝，非真死；性不主动伤人。',
    shape: '鱼身如牛，蛇尾有翼，胁下生羽。',
    sound: '其音如留牛，低沉哞哞。',
    effect: '食之无肿疾',
    tier: 3,
    base: { hp: 80, atk: 15, def: 6, spd: 9 },
    exp: 34,
    mountains: ['dishan'],
    kit: {
      passive: '冬死夏生',
      passiveDesc: '佩戴后每场战斗首次致死伤害时保留一线生机。',
      active: { name: '冬蛰', desc: '收翼蛰伏，本回合受伤减半并回复气。' },
    },
    drops: ['luyu'],
    art: { tint: '#5a7d8c', silhouette: 'fish', marks: 2 },
  },
  {
    id: 'lei',
    name: '类',
    quote: '又东四百里，曰亶爰之山，多水，无草木，不可以上。有兽焉，其状如狸而有髦，其名曰类，自为牝牡，食者不妒。',
    plain: '亶爰山多水无草木，不可攀上。有一种兽，形状像野猫而头上有发，名叫类，一身兼具雌雄两性。吃了它的肉，人就不生妒忌心。',
    nature: '双身一体，不争不妒，遇敌多以静制动。',
    shape: '形如狸而头上有长毛（髦）。',
    sound: '几乎不叫，只在天光将暗时低鸣一声。',
    effect: '食者不妒',
    tier: 3,
    base: { hp: 65, atk: 13, def: 6, spd: 13 },
    exp: 36,
    mountains: ['danyuan'],
    kit: {
      passive: '不妒',
      passiveDesc: '佩戴后气上限 +6。',
      active: { name: '自化', desc: '阴阳自转，回复大半气力。' },
    },
    drops: ['leirou'],
    art: { tint: '#8c7a5e', silhouette: 'cat', marks: 1 },
  },
  {
    id: 'boyi',
    name: '猼訑',
    pinyin: 'bó yí',
    quote: '又东三百里，曰基山，其阳多玉，其阴多怪木。有兽焉，其状如羊，九尾四耳，其目在背，其名曰猼訑，佩之不畏。',
    plain: '基山阳面多玉，阴面多怪木。有一种兽，形状像羊，九条尾巴四只耳朵，眼睛长在背上，名叫猼訑。佩戴它的皮毛，人就不知恐惧。',
    nature: '目在背，故从不正眼视人；受惊即以九尾扫尘遁走。',
    shape: '羊身，九尾四耳，眼睛长在背上。',
    sound: '咩声重叠，仿佛九只羊同叫。',
    effect: '佩之不畏',
    tier: 3,
    base: { hp: 85, atk: 16, def: 8, spd: 8 },
    exp: 40,
    mountains: ['jishan'],
    kit: {
      passive: '不畏',
      passiveDesc: '佩戴后免疫「惧」。',
      active: { name: '背目', desc: '背上的眼睛一睁，直接识破一层。' },
    },
    drops: ['boyi_pi'],
    art: { tint: '#b09a6a', silhouette: 'ram', marks: 9 },
  },
  {
    id: 'changfu',
    name: '𪁺𩿧',
    pinyin: 'chāng fú',
    quote: '有鸟焉，其状如鸡而三首、六目、六足、三翼，其名曰𪁺𩿧，食之无卧。',
    plain: '有一种鸟，形状像鸡却有三个头、六只眼、六只脚、三只翅膀，名叫𪁺𩿧。吃了它的肉，人就不必多睡、精神百倍。',
    nature: '三首各行其是，常自争吵；性躁而快。',
    shape: '状如鸡，三首六目六足三翼。',
    sound: '三首齐鸣，此起彼伏如争辩。',
    effect: '食之无卧',
    tier: 3,
    base: { hp: 60, atk: 17, def: 5, spd: 15 },
    exp: 38,
    mountains: ['jishan'],
    kit: {
      passive: '无卧',
      passiveDesc: '佩戴后身法 +3。',
      active: { name: '三首瞰', desc: '三个头同时下扑，伤害大增。' },
    },
    drops: ['changyu'],
    art: { tint: '#a8552e', silhouette: 'bird', marks: 3 },
  },
  {
    id: 'guanguan',
    name: '灌灌',
    quote: '有鸟焉，其状如鸠，其音如呵，名曰灌灌，佩之不惑。',
    plain: '青丘山有一种鸟，形状像斑鸠，叫声像人呵斥，名叫灌灌。佩戴它就不受迷惑。',
    nature: '护巢极凶，呵斥声正是逐人的手段。',
    shape: '形如斑鸠，羽有青光。',
    sound: '其音如呵——像有人在厉声喝止你。',
    effect: '佩之不惑',
    tier: 3,
    base: { hp: 55, atk: 15, def: 6, spd: 14 },
    exp: 40,
    mountains: ['qingqiu'],
    kit: {
      passive: '不惑',
      passiveDesc: '佩戴后免疫「迷」。',
      active: { name: '呵音', desc: '厉声一喝，敌方下次攻击可能落空。' },
    },
    drops: ['guanyu'],
    art: { tint: '#4a7d6b', silhouette: 'bird', marks: 0 },
  },
  {
    id: 'chiru',
    name: '赤鱬',
    pinyin: 'chì rú',
    quote: '英水出焉，南流注于即翼之泽。其中多赤鱬，其状如鱼而人面，其音如鸯鸳，食之不疥。',
    plain: '英水中多赤鱬，鱼的身子却是人的面孔，叫声像鸳鸯。吃了它不生疥疮。',
    nature: '人面有悲喜，性温顺，喜近灯火。',
    shape: '鱼身人面，通体赤色。',
    sound: '其音如鸳鸯，双双和鸣。',
    effect: '食之不疥',
    tier: 3,
    base: { hp: 70, atk: 16, def: 7, spd: 12 },
    exp: 44,
    mountains: ['qingqiu', 'jiwei'],
    kit: {
      passive: '不疥',
      passiveDesc: '佩戴后免疫瘴。',
      active: { name: '人面悯', desc: '人面作悯色，解毒并回复生命。' },
    },
    drops: ['chiru_zhu'],
    art: { tint: '#c25a4a', silhouette: 'fish', marks: 0 },
  },
  {
    id: 'jiuwei',
    name: '九尾狐',
    quote: '有兽焉，其状如狐而九尾，其音如婴儿，能食人，食者不蛊。',
    plain: '青丘山有兽，形如狐而生九尾，叫声像婴儿，能吃人；但吃了它的肉，人就不受妖邪蛊惑。凶与祥一体两面。',
    nature: '千年问兽者功课：识其性，不惧其名。它近人时声如婴儿，最险。',
    shape: '狐身九尾，尾如帚而散如焰。',
    sound: '其音如婴儿——夜里听来最是要小心。',
    effect: '食者不蛊',
    tier: 5,
    base: { hp: 130, atk: 22, def: 10, spd: 14 },
    exp: 90,
    mountains: ['qingqiu'],
    kit: {
      passive: '不蛊',
      passiveDesc: '佩戴后攻击提高一成。',
      active: { name: '婴啼', desc: '婴儿啼声惑敌，敌方攻击大减三回合。' },
    },
    drops: ['jiuwei_wei'],
    art: { tint: '#d8a24e', silhouette: 'fox', marks: 9 },
  },
];

export function getBeast(id: string): BeastTemplate | undefined {
  return BEASTS.find((b) => b.id === id);
}

/** 瘴化强化：山主/精英共用乘数。 */
export function scaleBeast(base: { hp: number; atk: number; def: number; spd: number }, level: number, elite = false) {
  const grow = (level - 1) / 29;
  const k = elite ? 1.5 : 1;
  return {
    maxHp: Math.round(base.hp * (1 + grow * 1.9) * k),
    atk: Math.round(base.atk * (1 + grow * 1.5) * k),
    def: Math.round(base.def * (1 + grow * 1.2)),
    spd: Math.round(base.spd * (1 + grow * 0.5)),
  };
}
