import type { OmenItem } from '../core/types.ts';

/**
 * 卜辞填空题库（30 题）。
 * 句式极短，重在让用户体验「甲骨文首先是问事的工具」。
 * 每题只挖一个甲骨字，blankId 为字形 id，options 为三个候选现代字。
 */
export const OMENS: OmenItem[] = [
  // 天象（6）
  {
    id: 'omen-rain',
    oracleText: '贞：今日□？',
    blankId: 'yu-rain',
    options: ['日', '雨', '月'],
    answer: 1,
    vernacular: '问：今天会下雨吗？',
    whyAsked: '雨水决定农时与出行，是卜辞中最常见的天气之问。',
  },
  {
    id: 'omen-sun',
    oracleText: '贞：□不蔽，明？',
    blankId: 'ri',
    options: ['月', '日', '火'],
    answer: 1,
    vernacular: '问：太阳不会被遮蔽，会明亮吗？',
    whyAsked: '日食或异常天象常引发占卜，反映对天时的重视。',
  },
  {
    id: 'omen-moon',
    oracleText: '□有食，祟？',
    blankId: 'yue',
    options: ['日', '月', '星'],
    answer: 1,
    vernacular: '问：月亮被食，是灾祸吗？',
    whyAsked: '月食被视为天象异常，商人会占卜是否预示祸祟。',
  },
  {
    id: 'omen-wind',
    oracleText: '贞：今日不□？',
    blankId: 'feng',
    options: ['雨', '风', '雷'],
    answer: 1,
    vernacular: '问：今天不会刮风吗？',
    whyAsked: '风会影响出行、田猎与祭祀，是重要的气象之问。',
  },
  {
    id: 'omen-thunder',
    oracleText: '贞：今夕其□？',
    blankId: 'lei',
    options: ['风', '雷', '星'],
    answer: 1,
    vernacular: '问：今晚会打雷吗？',
    whyAsked: '雷声常和雨水、神怒关联，商人不时为此卜问。',
  },
  {
    id: 'omen-stars',
    oracleText: '□夕大现，有来告？',
    blankId: 'xing',
    options: ['日', '星', '月'],
    answer: 1,
    vernacular: '问：星星今夜大亮，会有消息传来吗？',
    whyAsked: '新星或异常星象常被赋予人事预兆。',
  },

  // 山川 / 自然（5）
  {
    id: 'omen-mountain',
    oracleText: '王涉□，无灾？',
    blankId: 'shan',
    options: ['山', '水', '田'],
    answer: 0,
    vernacular: '问：大王翻山，没有灾祸吗？',
    whyAsked: '商王出行常因山川险阻而占卜。',
  },
  {
    id: 'omen-water',
    oracleText: '涉□，其遘鱼？',
    blankId: 'shui',
    options: ['水', '河', '雨'],
    answer: 0,
    vernacular: '问：渡水，会碰到鱼吗？',
    whyAsked: '涉水捕鱼与祭祀用鱼都是常见事由。',
  },
  {
    id: 'omen-wood',
    oracleText: '于□木燎，吉？',
    blankId: 'mu',
    options: ['林', '木', '火'],
    answer: 1,
    vernacular: '问：在木旁举行燎祭，吉利吗？',
    whyAsked: '木柴是燎祭的重要燃料，地点也常卜问。',
  },
  {
    id: 'omen-forest',
    oracleText: '王其田于□，擒？',
    blankId: 'lin',
    options: ['山', '林', '田'],
    answer: 1,
    vernacular: '问：大王在林中田猎，能捕获吗？',
    whyAsked: '林中是田猎佳地，也暗含迷路或猛兽之忧。',
  },
  {
    id: 'omen-fire',
    oracleText: '□燎于祊，有雨？',
    blankId: 'huo',
    options: ['风', '火', '水'],
    answer: 1,
    vernacular: '问：用火在祊燎祭，会下雨吗？',
    whyAsked: '燎祭以烟气上达神明，同时盼望降下甘霖。',
  },

  // 人体 / 动作（5）
  {
    id: 'omen-person',
    oracleText: '□来告，有疾？',
    blankId: 'ren',
    options: ['王', '人', '女'],
    answer: 1,
    vernacular: '问：有人来报告，是有疾病吗？',
    whyAsked: '他人来报往往伴随疾病、消息等不确定事件。',
  },
  {
    id: 'omen-woman',
    oracleText: '□□娩，嘉？',
    blankId: 'nv',
    options: ['女', '母', '人'],
    answer: 0,
    vernacular: '问：女子分娩，会顺利吗？',
    whyAsked: '生育是王室与贵族最关心的吉凶之一。',
  },
  {
    id: 'omen-mouth',
    oracleText: '王其□疾，勿唯蛊？',
    blankId: 'kou',
    options: ['目', '口', '耳'],
    answer: 1,
    vernacular: '问：大王口腔有疾，不是蛊疾吗？',
    whyAsked: '商代已有按身体部位占卜疾病的记录。',
  },
  {
    id: 'omen-see',
    oracleText: '王□月，明？',
    blankId: 'jian',
    options: ['见', '望', '来'],
    answer: 0,
    vernacular: '问：大王看见月亮，会明亮吗？',
    whyAsked: '「见」表示目有所见，也引申为获得征兆。',
  },
  {
    id: 'omen-look',
    oracleText: '王登□，无祸？',
    blankId: 'wang-look',
    options: ['望', '山', '门'],
    answer: 0,
    vernacular: '问：大王登高远望，没有灾祸吗？',
    whyAsked: '登高望远常和祭祀、观察天象等仪式结合。',
  },

  // 动物 / 田猎（5）
  {
    id: 'omen-dog',
    oracleText: '田□，其擒？',
    blankId: 'quan',
    options: ['马', '犬', '鹿'],
    answer: 1,
    vernacular: '问：带着犬田猎，能捕获吗？',
    whyAsked: '犬是田猎的得力助手，也常用于守卫。',
  },
  {
    id: 'omen-cattle',
    oracleText: '□其疫，不其死？',
    blankId: 'niu',
    options: ['羊', '犬', '牛'],
    answer: 2,
    vernacular: '问：牛会生疫病，不会死吗？',
    whyAsked: '牛是重要畜力与祭牲，疫情牵动国力。',
  },
  {
    id: 'omen-horse',
    oracleText: '王其□，其遘鹿？',
    blankId: 'ma',
    options: ['车', '马', '犬'],
    answer: 1,
    vernacular: '问：大王骑马，能遇到鹿吗？',
    whyAsked: '马是田猎与战争的重要工具。',
  },
  {
    id: 'omen-deer',
    oracleText: '擒□，获百？',
    blankId: 'lu',
    options: ['兔', '鹿', '虎'],
    answer: 1,
    vernacular: '问：捕获鹿，能到一百头吗？',
    whyAsked: '鹿是田猎中常见且具象征意义的猎物。',
  },
  {
    id: 'omen-bird',
    oracleText: '□来集，有祸？',
    blankId: 'niao',
    options: ['犬', '鱼', '鸟'],
    answer: 2,
    vernacular: '问：鸟飞来聚集，会有祸吗？',
    whyAsked: '鸟类异动常被视作自然征兆。',
  },

  // 器物 / 建筑 / 方位（5）
  {
    id: 'omen-above',
    oracleText: '燎于□，受年？',
    blankId: 'shang',
    options: ['上', '下', '中'],
    answer: 0,
    vernacular: '问：向上举行燎祭，会有好年成吗？',
    whyAsked: '上方是神明所在，燎祭烟气上达以求丰收。',
  },
  {
    id: 'omen-below',
    oracleText: '□示于河，吉？',
    blankId: 'xia',
    options: ['上', '下', '中'],
    answer: 1,
    vernacular: '问：向下在河神前展示祭品，吉利吗？',
    whyAsked: '下方与河流、阴界相关，是祭祀方位之问。',
  },
  {
    id: 'omen-field',
    oracleText: '□□受年？',
    blankId: 'tian',
    options: ['田', '山', '土'],
    answer: 0,
    vernacular: '问：田地会有好收成吗？',
    whyAsked: '「受年」是农业社会最关心的问题之一。',
  },
  {
    id: 'omen-gate',
    oracleText: '王立于□，无祸？',
    blankId: 'men',
    options: ['门', '户', '宗'],
    answer: 0,
    vernacular: '问：大王立于门前，没有灾祸吗？',
    whyAsked: '门是宫室与宗庙的出入口，也是仪式空间。',
  },
  {
    id: 'omen-vehicle',
    oracleText: '贞：王□往，来无祸？',
    blankId: 'che',
    options: ['车', '舟', '马'],
    answer: 0,
    vernacular: '问：大王乘车前往，往返没有灾祸吗？',
    whyAsked: '商王出行常事前占卜，以确保路途平安。',
  },

  // 祭祀 / 权力（4）
  {
    id: 'omen-crack',
    oracleText: '□之，王占曰吉。',
    blankId: 'bu',
    options: ['卜', '贞', '祝'],
    answer: 0,
    vernacular: '卜问之后，大王占卜说吉利。',
    whyAsked: '卜字本身记录的就是甲骨占卜的裂纹。',
  },
  {
    id: 'omen-ask',
    oracleText: '□□旬无祸？',
    blankId: 'zhen',
    options: ['卜', '贞', '祝'],
    answer: 1,
    vernacular: '问：贞问这一旬没有灾祸吗？',
    whyAsked: '贞是引出卜辞问句的常用字。',
  },
  {
    id: 'omen-king',
    oracleText: '□其征土方，受佑？',
    blankId: 'wang',
    options: ['帝', '王', '祖'],
    answer: 1,
    vernacular: '问：大王征讨土方，会得到保佑吗？',
    whyAsked: '商王出征是大事，常先卜问吉凶。',
  },
  {
    id: 'omen-sacrifice',
    oracleText: '贞：翌日燎于□？',
    blankId: 'yang',
    options: ['王', '火', '羊'],
    answer: 2,
    vernacular: '问：明天用羊来燎祭吗？',
    whyAsked: '羊是常见祭牲，燎祭以烟气上达神明。',
  },
];

export function getOmenById(id: string): OmenItem | undefined {
  return OMENS.find((o) => o.id === id);
}
