#!/usr/bin/env python3
"""Import the MIT-declared JiaGuWen reference corpus into the game catalog.

The upstream repository provides modern-character labels plus 50px oracle-form
images. This script records the upstream URL and keeps the imported data in a
separate reference layer; it does not turn unreviewed labels into game questions.
"""

from __future__ import annotations

import json
import time
from io import BytesIO
from pathlib import Path
from zipfile import ZipFile
from urllib.request import Request, urlopen

REPO = "https://raw.githubusercontent.com/Chinese-Traditional-Culture/JiaGuWen/master"
INDEX_URL = f"{REPO}/index.json"
ARCHIVE_URL = "https://codeload.github.com/Chinese-Traditional-Culture/JiaGuWen/zip/refs/heads/master"
ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "public" / "glyphs" / "corpus"
OUTPUT = ROOT / "src" / "games" / "jiaguwen" / "content" / "oracleCatalog.generated.ts"


def fetch(url: str) -> bytes:
    request = Request(url, headers={"User-Agent": "rex-game-oracle-corpus-import"})
    for attempt in range(3):
        try:
            with urlopen(request, timeout=30) as response:
                return response.read()
        except OSError:
            if attempt == 2:
                raise
            time.sleep(1 + attempt)
    raise AssertionError("unreachable")


def main() -> None:
    index = json.loads(fetch(INDEX_URL).decode("utf-8"))
    if not isinstance(index, list) or len(index) < 1000:
        raise ValueError("Unexpected upstream catalog; expected at least 1000 forms")

    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    forms: list[tuple[str, str]] = []
    missing: list[str] = []
    for item in index:
        filename = item["image"]
        modern = item["name"]
        if not isinstance(filename, str) or not isinstance(modern, str):
            raise ValueError("Unexpected item in upstream catalog")
        if not (ASSET_DIR / filename).exists():
            missing.append(filename)
        forms.append((Path(filename).stem, modern))

    if missing:
        with ZipFile(BytesIO(fetch(ARCHIVE_URL))) as archive:
            for filename in missing:
                member = f"JiaGuWen-master/i/{filename}"
                (ASSET_DIR / filename).write_bytes(archive.read(member))

    forms.sort(key=lambda form: form[0])

    lines = [
        "// Generated by scripts/import-open-oracle-catalog.py. Do not edit manually.",
        "// Source: Chinese-Traditional-Culture/JiaGuWen (upstream README declares MIT).",
        "import type { OracleCatalogForm } from '../core/types.ts';",
        "",
        "export const OPEN_ORACLE_CATALOG: OracleCatalogForm[] = [",
    ]
    lines.extend(
        f"  {{ id: 'jgw-{form_id}', modern: {modern!r}, image: '/glyphs/corpus/{form_id}.jpg', sourceId: 'jgw-open', formType: 'reference-glyph', license: 'MIT (upstream README declaration)', sourceRecordUrl: '{REPO}/i/{form_id}.jpg', retrievedAt: '2026-07-27' }},"
        for form_id, modern in forms
    )
    lines.extend([
        "];",
        "",
        "export const OPEN_ORACLE_CATALOG_HEAD_COUNT = new Set(OPEN_ORACLE_CATALOG.map((form) => form.modern)).size;",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Imported {len(forms)} form samples and {len(set(modern for _, modern in forms))} labeled heads.")


if __name__ == "__main__":
    main()
