#!/usr/bin/env python3
"""Build a CC0 Xiaoxuetang corpus from a reviewed query-export manifest.

Do not scrape protected routes. The manifest must be produced from the official
query interface or an authorized export, and must preserve a source record URL,
source index, license, and retrieval date for every glyph form.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "data" / "xiaoxue-oracle-manifest.json"
ASSET_DIR = ROOT / "public" / "glyphs" / "xiaoxue"
OUTPUT = ROOT / "src" / "games" / "jiaguwen" / "content" / "xiaoxueCatalog.generated.ts"


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    manifest_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_MANIFEST
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    forms = manifest.get("forms")
    if not isinstance(forms, list) or not forms:
        raise ValueError("Manifest requires a non-empty forms array")
    allow_partial = "--allow-partial" in sys.argv
    head_count = len({item["modern"] for item in forms if isinstance(item, dict) and isinstance(item.get("modern"), str)})
    if head_count < 1000 and not allow_partial:
        raise ValueError(f"Expected at least 1000 headwords, received {head_count}; pass --allow-partial only for development imports")

    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    generated = [
        "// Generated by scripts/import-xiaoxue-catalog.py. Do not edit manually.",
        "import type { OracleCatalogForm } from '../core/types.ts';",
        "",
        "export const XIAOXUE_ORACLE_CATALOG: OracleCatalogForm[] = [",
    ]
    seen_ids: set[str] = set()
    for item in forms:
        required = ("id", "modern", "source_file", "source_record_url", "retrieved_at")
        if not isinstance(item, dict) or any(not isinstance(item.get(key), str) or not item[key] for key in required):
            raise ValueError(f"Each form requires string fields: {', '.join(required)}")
        form_id = item["id"]
        if form_id in seen_ids:
            raise ValueError(f"Duplicate form id: {form_id}")
        seen_ids.add(form_id)
        source_file = (manifest_path.parent / item["source_file"]).resolve()
        if not source_file.is_file():
            raise FileNotFoundError(source_file)
        extension = source_file.suffix.lower()
        if extension not in {".png", ".jpg", ".jpeg", ".webp"}:
            raise ValueError(f"Unsupported glyph image type: {source_file.name}")
        destination_name = f"{form_id}{extension}"
        shutil.copyfile(source_file, ASSET_DIR / destination_name)
        generated.append(
            "  { "
            f"id: {q(form_id)}, modern: {q(item['modern'])}, image: {q('/glyphs/xiaoxue/' + destination_name)}, "
            "sourceId: 'xiaoxue', formType: 'reference-glyph', license: 'CC0-1.0', "
            f"sourceRecordUrl: {q(item['source_record_url'])}, retrievedAt: {q(item['retrieved_at'])} "
            "},"
        )
    generated.extend([
        "];",
        "",
        "export const XIAOXUE_ORACLE_HEAD_COUNT = new Set(XIAOXUE_ORACLE_CATALOG.map((form) => form.modern)).size;",
    ])
    OUTPUT.write_text("\n".join(generated), encoding="utf-8")
    print(f"Imported {len(forms)} Xiaoxuetang forms from {manifest_path}.")


if __name__ == "__main__":
    main()
